"""
Script d'ajout des nouvelles commandes au bot CoC
Lance avec : python3 add_commands.py
"""
import os
BASE = os.path.expanduser("~/coc-bot")

# ══════════════════════════════════════════
# DB update — nouvelles tables
# ══════════════════════════════════════════
open(f"{BASE}/database.py", "w").write(
'import aiosqlite\n'
'import time\n'
'import os\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'DB_PATH = os.getenv("DB_PATH", "data/bot.db")\n'
'\n'
'async def init_db():\n'
'    async with aiosqlite.connect(DB_PATH) as db:\n'
'        await db.executescript("""\n'
'            CREATE TABLE IF NOT EXISTS cache (\n'
'                cache_key TEXT PRIMARY KEY,\n'
'                value TEXT,\n'
'                source TEXT,\n'
'                created INTEGER\n'
'            );\n'
'            CREATE TABLE IF NOT EXISTS logs (\n'
'                id INTEGER PRIMARY KEY AUTOINCREMENT,\n'
'                guild_id TEXT, user_id TEXT, command TEXT,\n'
'                result TEXT, ai_used TEXT, cost REAL, created INTEGER\n'
'            );\n'
'            CREATE TABLE IF NOT EXISTS blacklist (\n'
'                user_id TEXT PRIMARY KEY, reason TEXT, created INTEGER\n'
'            );\n'
'            CREATE TABLE IF NOT EXISTS rate_limit (\n'
'                user_id TEXT PRIMARY KEY, count INTEGER, window_start INTEGER\n'
'            );\n'
'            CREATE TABLE IF NOT EXISTS feedback (\n'
'                id INTEGER PRIMARY KEY AUTOINCREMENT,\n'
'                user_id TEXT, guild_id TEXT, lien TEXT,\n'
'                note INTEGER, commentaire TEXT, created INTEGER\n'
'            );\n'
'            CREATE TABLE IF NOT EXISTS replays_3stars (\n'
'                id INTEGER PRIMARY KEY AUTOINCREMENT,\n'
'                player_tag TEXT, guild_id TEXT,\n'
'                hdv INTEGER, base_type TEXT, compo TEXT,\n'
'                lien TEXT, note TEXT, created INTEGER\n'
'            );\n'
'        """)\n'
'        await db.commit()\n'
'\n'
'async def get_cache(key):\n'
'    try:\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute("SELECT value, created FROM cache WHERE cache_key=?", (key,)) as c:\n'
'                row = await c.fetchone()\n'
'                if row and (time.time() - row[1]) < 86400:\n'
'                    return row[0]\n'
'    except Exception:\n'
'        pass\n'
'    return None\n'
'\n'
'async def set_cache(key, value, source="", hours=24):\n'
'    try:\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute(\n'
'                "INSERT OR REPLACE INTO cache (cache_key, value, source, created) VALUES (?,?,?,?)",\n'
'                (key, value, source, int(time.time()))\n'
'            )\n'
'            await db.commit()\n'
'    except Exception:\n'
'        pass\n'
'\n'
'async def is_blacklisted(user_id):\n'
'    try:\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute("SELECT 1 FROM blacklist WHERE user_id=?", (user_id,)) as c:\n'
'                return await c.fetchone() is not None\n'
'    except Exception:\n'
'        return False\n'
'\n'
'async def check_rate_limit(user_id, limit=10, window=3600):\n'
'    try:\n'
'        now = int(time.time())\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute("SELECT count, window_start FROM rate_limit WHERE user_id=?", (user_id,)) as c:\n'
'                row = await c.fetchone()\n'
'            if row:\n'
'                count, start = row\n'
'                if now - start > window:\n'
'                    await db.execute("UPDATE rate_limit SET count=1, window_start=? WHERE user_id=?", (now, user_id))\n'
'                elif count >= limit:\n'
'                    await db.commit()\n'
'                    return False\n'
'                else:\n'
'                    await db.execute("UPDATE rate_limit SET count=count+1 WHERE user_id=?", (user_id,))\n'
'            else:\n'
'                await db.execute("INSERT INTO rate_limit (user_id, count, window_start) VALUES (?,1,?)", (user_id, now))\n'
'            await db.commit()\n'
'        return True\n'
'    except Exception:\n'
'        return True\n'
'\n'
'async def log_command(guild_id, user_id, command, result, ai_used="", cost=0.0):\n'
'    try:\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute(\n'
'                "INSERT INTO logs (guild_id, user_id, command, result, ai_used, cost, created) VALUES (?,?,?,?,?,?,?)",\n'
'                (str(guild_id), str(user_id), command, result, ai_used, cost, int(time.time()))\n'
'            )\n'
'            await db.commit()\n'
'    except Exception:\n'
'        pass\n'
)
print("OK: database.py")

# ══════════════════════════════════════════
# cogs/bases.py
# ══════════════════════════════════════════
open(f"{BASE}/cogs/bases.py", "w").write(
'import discord, os, time, aiosqlite\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from database import log_command, is_blacklisted, check_rate_limit, get_cache, set_cache\n'
'from ai_cascade import ask_ai\n'
'from sources import get_all_sources, format_sources\n'
'\n'
'DB_PATH = os.getenv("DB_PATH", "data/bot.db")\n'
'\n'
'class Bases(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="copybase", description="Analyse un screenshot et trouve 5 bases similaires")\n'
'    @app_commands.describe(hdv="Ton HDV (1-18)", type_base="Type de base (diamond/box/ring/anti3)")\n'
'    async def copybase(self, interaction: discord.Interaction, hdv: int, type_base: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        sources = await get_all_sources("meilleure base HDV"+str(hdv)+" "+type_base, hdv)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            ctx + "\\n\\n"\n'
'            + "Trouve 5 bases Clash of Clans de type " + type_base + " pour HDV" + str(hdv) + ".\\n"\n'
'            + "Pour chaque base donne : type de base, style defensif, points forts, points faibles.\\n"\n'
'            + "Utilise les vraies bases CoC connues. Sois precis."\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Bases HDV"+str(hdv)+" - "+type_base, description=result[:4000], color=0x27AE60)\n'
'        if sources:\n'
'            links = "\\n".join([v["url"] for v in sources[:3] if v.get("url")])\n'
'            if links:\n'
'                embed.add_field(name="Sources", value=links, inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "copybase", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="attack", description="Strategie complete pour attaquer une base CoC")\n'
'    @app_commands.describe(hdv_adverse="HDV de la base a attaquer", ton_hdv="Ton HDV", style_base="Style base (diamond/box/ring/anti3)")\n'
'    async def attack(self, interaction: discord.Interaction, hdv_adverse: int, ton_hdv: int, style_base: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        sources = await get_all_sources("attaque HDV"+str(hdv_adverse)+" "+style_base+" strategie", hdv_adverse)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            ctx + "\\n\\n"\n'
'            + "Strategie complète pour attaquer une base " + style_base + " HDV" + str(hdv_adverse) + " avec un HDV" + str(ton_hdv) + ".\\n"\n'
'            + "1) Composition optimale avec vraies troupes CoC et quantites exactes\\n"\n'
'            + "2) Sorts recommandes\\n"\n'
'            + "3) Point d entree ideal\\n"\n'
'            + "4) Ordre de deploiement etape par etape\\n"\n'
'            + "5) Pieges a eviter sur ce type de base\\n"\n'
'            + "6) Probabilite 2 etoiles et 3 etoiles"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Attaque Base "+style_base+" HDV"+str(hdv_adverse), description=result[:4000], color=0xE74C3C)\n'
'        if sources:\n'
'            links = "\\n".join([v["url"] for v in sources[:3] if v.get("url")])\n'
'            if links:\n'
'                embed.add_field(name="Replays YouTube", value=links, inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "attack", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="piege", description="Detecte les pieges sur une base - score de dangerosite 1-10")\n'
'    @app_commands.describe(hdv="HDV de la base", style_base="Style (diamond/box/ring/anti3)", compo="Ta compo d attaque")\n'
'    async def piege(self, interaction: discord.Interaction, hdv: int, style_base: str, compo: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        prompt = (\n'
'            "Analyse des pieges Clash of Clans sur une base " + style_base + " HDV" + str(hdv) + ".\\n"\n'
'            + "Compo d attaque : " + compo + "\\n"\n'
'            + "1) Emplacements typiques des pieges sur ce type de base\\n"\n'
'            + "2) Pieges les plus dangereux pour " + compo + "\\n"\n'
'            + "3) Score de dangerosite global : /10\\n"\n'
'            + "4) Comment contourner ces pieges\\n"\n'
'            + "5) Zones a eviter absolument"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Analyse Pieges - "+style_base+" HDV"+str(hdv), description=result[:4000], color=0xE67E22)\n'
'        embed.set_footer(text="IA : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "piege", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="add3star", description="Ajoute un replay 3 etoiles a la bibliotheque du clan")\n'
'    @app_commands.describe(hdv="HDV de la base attackee", type_base="Type de base", compo="Compo utilisee", lien="Lien replay ou video")\n'
'    async def add3star(self, interaction: discord.Interaction, hdv: int, type_base: str, compo: str, lien: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute(\n'
'                "INSERT INTO replays_3stars (player_tag, guild_id, hdv, base_type, compo, lien, note, created) VALUES (?,?,?,?,?,?,?,?)",\n'
'                (str(interaction.user.id), str(interaction.guild_id), hdv, type_base, compo, lien, "3 etoiles", int(time.time()))\n'
'            )\n'
'            await db.commit()\n'
'        embed = discord.Embed(\n'
'            title="Replay 3 etoiles ajoute !",\n'
'            description="HDV"+str(hdv)+" | "+type_base+" | "+compo+"\\n"+lien,\n'
'            color=0xF1C40F\n'
'        )\n'
'        embed.set_footer(text="Ajoute par "+str(interaction.user.name))\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "add3star", "ok", "", 0)\n'
'\n'
'    @app_commands.command(name="3stars", description="Cherche des replays 3 etoiles dans la bibliotheque")\n'
'    @app_commands.describe(hdv="HDV de la base", type_base="Type de base (optionnel)", compo="Compo (optionnel)")\n'
'    async def stars3(self, interaction: discord.Interaction, hdv: int, type_base: str = "", compo: str = ""):\n'
'        await interaction.response.defer()\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            query = "SELECT player_tag, hdv, base_type, compo, lien, created FROM replays_3stars WHERE guild_id=? AND hdv=?"\n'
'            params = [str(interaction.guild_id), hdv]\n'
'            if type_base:\n'
'                query += " AND base_type=?"\n'
'                params.append(type_base)\n'
'            if compo:\n'
'                query += " AND compo LIKE ?"\n'
'                params.append("%" + compo + "%")\n'
'            query += " ORDER BY created DESC LIMIT 10"\n'
'            async with db.execute(query, params) as c:\n'
'                rows = await c.fetchall()\n'
'        if not rows:\n'
'            await interaction.followup.send("Aucun replay trouve pour ces criteres.", ephemeral=True)\n'
'            return\n'
'        embed = discord.Embed(title="Replays 3 etoiles HDV"+str(hdv), color=0xF1C40F)\n'
'        for r in rows:\n'
'            embed.add_field(\n'
'                name=r[2]+" | "+r[3],\n'
'                value=r[4][:100],\n'
'                inline=False\n'
'            )\n'
'        await interaction.followup.send(embed=embed)\n'
'\n'
'    @app_commands.command(name="mes3stars", description="Tes replays 3 etoiles classes par HDV")\n'
'    async def mes3stars(self, interaction: discord.Interaction):\n'
'        await interaction.response.defer()\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute(\n'
'                "SELECT hdv, base_type, compo, lien, created FROM replays_3stars WHERE player_tag=? ORDER BY created DESC LIMIT 20",\n'
'                (str(interaction.user.id),)\n'
'            ) as c:\n'
'                rows = await c.fetchall()\n'
'        if not rows:\n'
'            await interaction.followup.send("Tu n as pas encore de replays 3 etoiles enregistres.", ephemeral=True)\n'
'            return\n'
'        embed = discord.Embed(title="Tes replays 3 etoiles", color=0xF1C40F)\n'
'        for r in rows:\n'
'            embed.add_field(name="HDV"+str(r[0])+" | "+r[1]+" | "+r[2], value=r[3][:100], inline=False)\n'
'        await interaction.followup.send(embed=embed)\n'
'\n'
'    @app_commands.command(name="stats3stars", description="Rapport de progression et compos efficaces")\n'
'    async def stats3stars(self, interaction: discord.Interaction):\n'
'        await interaction.response.defer()\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute(\n'
'                "SELECT hdv, base_type, compo, COUNT(*) as nb FROM replays_3stars WHERE player_tag=? GROUP BY hdv, compo ORDER BY nb DESC",\n'
'                (str(interaction.user.id),)\n'
'            ) as c:\n'
'                rows = await c.fetchall()\n'
'        if not rows:\n'
'            await interaction.followup.send("Aucune statistique disponible.", ephemeral=True)\n'
'            return\n'
'        total = sum(r[3] for r in rows)\n'
'        prompt = (\n'
'            "Rapport de progression Clash of Clans base sur ces donnees de replays :\\n"\n'
'            + "\\n".join(["HDV"+str(r[0])+" "+r[2]+" x"+str(r[3]) for r in rows[:10]])\n'
'            + "\\nTotal : "+str(total)+" replays 3 etoiles.\\n"\n'
'            + "1) Compos les plus efficaces\\n"\n'
'            + "2) Progression observee\\n"\n'
'            + "3) Recommandations pour progresser davantage"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Tes stats 3 etoiles", description=result[:4000], color=0xF1C40F)\n'
'        embed.set_footer(text="Total : "+str(total)+" replays | IA : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'\n'
'    @app_commands.command(name="library", description="Bibliotheque complete des replays du clan par HDV et type de base")\n'
'    @app_commands.describe(hdv="HDV de la base", type_base="Type de base (diamond/box/ring/anti3)")\n'
'    async def library(self, interaction: discord.Interaction, hdv: int, type_base: str):\n'
'        await interaction.response.defer()\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute(\n'
'                "SELECT player_tag, compo, lien, created FROM replays_3stars WHERE guild_id=? AND hdv=? AND base_type=? ORDER BY created DESC LIMIT 20",\n'
'                (str(interaction.guild_id), hdv, type_base)\n'
'            ) as c:\n'
'                rows = await c.fetchall()\n'
'        if not rows:\n'
'            await interaction.followup.send("Aucun replay dans la bibliotheque pour HDV"+str(hdv)+" "+type_base+".", ephemeral=True)\n'
'            return\n'
'        embed = discord.Embed(title="Bibliotheque HDV"+str(hdv)+" - "+type_base, color=0x8E44AD)\n'
'        for r in rows:\n'
'            embed.add_field(name=r[1], value=r[2][:100], inline=False)\n'
'        embed.set_footer(text=str(len(rows))+" replays disponibles")\n'
'        await interaction.followup.send(embed=embed)\n'
'\n'
'    @app_commands.command(name="feedback", description="Donner un avis sur une base ou un replay")\n'
'    @app_commands.describe(lien="Lien de la base ou replay", note="Note de 1 a 5", commentaire="Ton commentaire")\n'
'    async def feedback(self, interaction: discord.Interaction, lien: str, note: int, commentaire: str = ""):\n'
'        await interaction.response.defer()\n'
'        if note < 1 or note > 5:\n'
'            await interaction.followup.send("La note doit etre entre 1 et 5.", ephemeral=True)\n'
'            return\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute(\n'
'                "INSERT INTO feedback (user_id, guild_id, lien, note, commentaire, created) VALUES (?,?,?,?,?,?)",\n'
'                (str(interaction.user.id), str(interaction.guild_id), lien, note, commentaire, int(time.time()))\n'
'            )\n'
'            await db.commit()\n'
'        stars = "⭐" * note\n'
'        embed = discord.Embed(title="Feedback enregistre !", color=0x2ECC71)\n'
'        embed.add_field(name="Note", value=stars, inline=True)\n'
'        embed.add_field(name="Lien", value=lien[:100], inline=True)\n'
'        if commentaire:\n'
'            embed.add_field(name="Commentaire", value=commentaire[:200], inline=False)\n'
'        embed.set_footer(text="Merci "+str(interaction.user.name)+" !")\n'
'        await interaction.followup.send(embed=embed)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Bases(bot))\n'
)
print("OK: cogs/bases.py")

# ══════════════════════════════════════════
# cogs/clan.py
# ══════════════════════════════════════════
open(f"{BASE}/cogs/clan.py", "w").write(
'import discord, os, requests\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from database import log_command, is_blacklisted, check_rate_limit, get_cache, set_cache\n'
'from ai_cascade import ask_ai\n'
'from sources import get_all_sources, format_sources\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'\n'
'COC_KEY = os.getenv("COC_API_KEY", "")\n'
'COC_BASE = "https://api.clashofclans.com/v1"\n'
'\n'
'def coc_get(endpoint):\n'
'    try:\n'
'        r = requests.get(\n'
'            COC_BASE + endpoint,\n'
'            headers={"Authorization": "Bearer " + COC_KEY},\n'
'            timeout=5\n'
'        )\n'
'        if r.status_code == 200:\n'
'            return r.json()\n'
'    except Exception as e:\n'
'        print("[CoC API]", e)\n'
'    return None\n'
'\n'
'class Clan(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="war", description="Analyse de guerre - fiche de chaque adversaire")\n'
'    @app_commands.describe(tag_clan="Tag de ton clan (ex: #ABC123)")\n'
'    async def war(self, interaction: discord.Interaction, tag_clan: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        tag = tag_clan.replace("#", "%23")\n'
'        war_data = coc_get("/clans/" + tag + "/currentwar")\n'
'        if not war_data or war_data.get("state") == "notInWar":\n'
'            await interaction.followup.send("Aucune guerre en cours pour ce clan.", ephemeral=True)\n'
'            return\n'
'        opponent = war_data.get("opponent", {})\n'
'        members = opponent.get("members", [])[:10]\n'
'        clan_name = opponent.get("name", "Adversaire")\n'
'        state = war_data.get("state", "")\n'
'        team_size = war_data.get("teamSize", 0)\n'
'        prompt = (\n'
'            "Analyse de guerre Clash of Clans.\\n"\n'
'            + "Clan adversaire : " + clan_name + " | Taille : " + str(team_size) + "v" + str(team_size) + "\\n"\n'
'            + "Etat : " + state + "\\n"\n'
'            + "Membres adverses (top 10) :\\n"\n'
'            + "\\n".join(["- " + m.get("name","?") + " HDV" + str(m.get("townhallLevel","?")) for m in members])\n'
'            + "\\n\\nDonne :\\n"\n'
'            + "1) Analyse generale de la composition adverse\\n"\n'
'            + "2) Joueurs prioritaires a attaquer\\n"\n'
'            + "3) Strategie recommandee avec vraies troupes CoC\\n"\n'
'            + "4) Points faibles du clan adverse\\n"\n'
'            + "5) Recommandations pour maximiser les etoiles"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Guerre vs " + clan_name, description=result[:4000], color=0xE74C3C)\n'
'        embed.add_field(name="Etat", value=state, inline=True)\n'
'        embed.add_field(name="Taille", value=str(team_size)+"v"+str(team_size), inline=True)\n'
'        embed.set_footer(text="IA : " + ai_used + " | API CoC")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "war", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="scout", description="Fiche complete d un clan ennemi")\n'
'    @app_commands.describe(tag_clan="Tag du clan ennemi (ex: #ABC123)")\n'
'    async def scout(self, interaction: discord.Interaction, tag_clan: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        tag = tag_clan.replace("#", "%23")\n'
'        clan_data = coc_get("/clans/" + tag)\n'
'        if not clan_data:\n'
'            await interaction.followup.send("Clan introuvable. Verifie le tag.", ephemeral=True)\n'
'            return\n'
'        name = clan_data.get("name", "?")\n'
'        level = clan_data.get("clanLevel", 0)\n'
'        war_wins = clan_data.get("warWins", 0)\n'
'        war_streak = clan_data.get("warWinStreak", 0)\n'
'        members_count = clan_data.get("members", 0)\n'
'        members = clan_data.get("memberList", [])[:15]\n'
'        th_counts = {}\n'
'        for m in members:\n'
'            th = m.get("townHallLevel", 0)\n'
'            th_counts[th] = th_counts.get(th, 0) + 1\n'
'        th_summary = " | ".join(["HDV"+str(k)+":"+str(v) for k,v in sorted(th_counts.items(), reverse=True)])\n'
'        sources = await get_all_sources("scout clan CoC strategie", None)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            ctx + "\\n\\n"\n'
'            + "Fiche de scouting Clash of Clans pour le clan : " + name + "\\n"\n'
'            + "Niveau clan : " + str(level) + " | Membres : " + str(members_count) + "\\n"\n'
'            + "Victoires en guerre : " + str(war_wins) + " | Serie actuelle : " + str(war_streak) + "\\n"\n'
'            + "Composition HDV : " + th_summary + "\\n"\n'
'            + "\\nDonne :\\n"\n'
'            + "1) Analyse de la composition du clan\\n"\n'
'            + "2) Points forts et points faibles\\n"\n'
'            + "3) Strategie recommandee pour les affronter\\n"\n'
'            + "4) Joueurs les plus dangereux (HDV les plus hauts)\\n"\n'
'            + "5) Niveau de menace general : /5"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Scout : " + name, description=result[:4000], color=0x8E44AD)\n'
'        embed.add_field(name="Niveau", value=str(level), inline=True)\n'
'        embed.add_field(name="Membres", value=str(members_count), inline=True)\n'
'        embed.add_field(name="Guerres gagnees", value=str(war_wins), inline=True)\n'
'        embed.add_field(name="Composition HDV", value=th_summary[:200] if th_summary else "N/A", inline=False)\n'
'        embed.set_footer(text="IA : " + ai_used + " | API CoC")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "scout", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="predict", description="Probabilite de victoire entre deux clans")\n'
'    @app_commands.describe(tag_clan1="Tag de ton clan", tag_clan2="Tag du clan adverse")\n'
'    async def predict(self, interaction: discord.Interaction, tag_clan1: str, tag_clan2: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        tag1 = tag_clan1.replace("#", "%23")\n'
'        tag2 = tag_clan2.replace("#", "%23")\n'
'        clan1 = coc_get("/clans/" + tag1)\n'
'        clan2 = coc_get("/clans/" + tag2)\n'
'        if not clan1 or not clan2:\n'
'            await interaction.followup.send("Un ou plusieurs clans introuvables.", ephemeral=True)\n'
'            return\n'
'        def clan_summary(c):\n'
'            members = c.get("memberList", [])[:15]\n'
'            th_avg = sum(m.get("townHallLevel",0) for m in members) / max(len(members),1)\n'
'            return (\n'
'                c.get("name","?") + " | Niveau " + str(c.get("clanLevel",0))\n'
'                + " | HDV moyen : " + str(round(th_avg,1))\n'
'                + " | Guerres gagnees : " + str(c.get("warWins",0))\n'
'            )\n'
'        prompt = (\n'
'            "Prediction de victoire Clash of Clans :\\n"\n'
'            + "Clan 1 : " + clan_summary(clan1) + "\\n"\n'
'            + "Clan 2 : " + clan_summary(clan2) + "\\n"\n'
'            + "\\nDonne :\\n"\n'
'            + "1) Probabilite de victoire pour chaque clan (en %)\\n"\n'
'            + "2) 3 matchups cles (quel joueur attaque qui)\\n"\n'
'            + "3) Avantages du clan 1\\n"\n'
'            + "4) Avantages du clan 2\\n"\n'
'            + "5) Facteur decisif qui determinera le vainqueur\\n"\n'
'            + "6) Niveau de confiance de la prediction : /10"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(\n'
'            title="Prediction : "+clan1.get("name","?")+" vs "+clan2.get("name","?"),\n'
'            description=result[:4000],\n'
'            color=0xF39C12\n'
'        )\n'
'        embed.set_footer(text="IA : "+ai_used+" | API CoC")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "predict", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="progression", description="Plan top 5 upgrades urgents via API CoC")\n'
'    @app_commands.describe(tag_joueur="Ton tag joueur (ex: #ABC123)")\n'
'    async def progression(self, interaction: discord.Interaction, tag_joueur: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        tag = tag_joueur.replace("#", "%23")\n'
'        player = coc_get("/players/" + tag)\n'
'        if not player:\n'
'            await interaction.followup.send("Joueur introuvable. Verifie le tag.", ephemeral=True)\n'
'            return\n'
'        name = player.get("name", "?")\n'
'        th = player.get("townHallLevel", 0)\n'
'        trophies = player.get("trophies", 0)\n'
'        heroes = player.get("heroes", [])\n'
'        troops = player.get("troops", [])\n'
'        hero_info = " | ".join([h.get("name","?")+" niv"+str(h.get("level","?"))+"/"+str(h.get("maxLevel","?")) for h in heroes])\n'
'        not_maxed = [t for t in troops if t.get("level",0) < t.get("maxLevel",1)][:5]\n'
'        troops_info = " | ".join([t.get("name","?")+" "+str(t.get("level","?"))+"/"+str(t.get("maxLevel","?")) for t in not_maxed])\n'
'        prompt = (\n'
'            "Plan de progression Clash of Clans pour " + name + ".\\n"\n'
'            + "HDV : " + str(th) + " | Trophees : " + str(trophies) + "\\n"\n'
'            + "Heros : " + (hero_info if hero_info else "aucun") + "\\n"\n'
'            + "Troupes pas max : " + (troops_info if troops_info else "tout max") + "\\n"\n'
'            + "\\nDonne :\\n"\n'
'            + "1) Top 5 upgrades URGENTS a faire maintenant\\n"\n'
'            + "2) Ordre optimal de progression\\n"\n'
'            + "3) Estimation du temps pour chaque upgrade\\n"\n'
'            + "4) Ressources a farmer en priorite\\n"\n'
'            + "5) Prochain objectif atteignable"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Progression de "+name+" (HDV"+str(th)+")", description=result[:4000], color=0x27AE60)\n'
'        embed.add_field(name="Trophees", value=str(trophies), inline=True)\n'
'        embed.add_field(name="HDV", value=str(th), inline=True)\n'
'        if hero_info:\n'
'            embed.add_field(name="Heros", value=hero_info[:200], inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used+" | API CoC")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "progression", "ok", ai_used, cost)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Clan(bot))\n'
)
print("OK: cogs/clan.py")

# ══════════════════════════════════════════
# Mise à jour bot.py pour charger les nouveaux cogs
# ══════════════════════════════════════════
bot_content = open(f"{BASE}/bot.py").read()
bot_content = bot_content.replace(
    'COGS = ["cogs.meta", "cogs.guerre", "cogs.coach", "cogs.info", "cogs.admin"]',
    'COGS = ["cogs.meta", "cogs.guerre", "cogs.coach", "cogs.info", "cogs.admin", "cogs.bases", "cogs.clan"]'
)
open(f"{BASE}/bot.py", "w").write(bot_content)
print("OK: bot.py mis a jour")

print("\n" + "="*50)
print("NOUVELLES COMMANDES AJOUTEES !")
print("="*50)
print("/copybase /attack /piege")
print("/add3star /3stars /mes3stars /stats3stars /library /feedback")
print("/war /scout /predict /progression")
print("\nLance : pkill -f 'python3 bot.py' && python3 bot.py")
