"""
SCRIPT DE CONSTRUCTION COMPLÈTE DU BOT COC
Lance avec : python3 build_bot.py
"""
import os

BASE = os.path.expanduser("~/coc-bot")
os.makedirs(f"{BASE}/cogs", exist_ok=True)
os.makedirs(f"{BASE}/data", exist_ok=True)

# ══════════════════════════════════════════
# .env.example
# ══════════════════════════════════════════
open(f"{BASE}/.env.example", "w").write(
"DISCORD_TOKEN=ton_token_discord\n"
"ANTHROPIC_API_KEY=sk-ant-...\n"
"GEMINI_API_KEY=AIza...\n"
"GROQ_API_KEY=gsk_...\n"
"YOUTUBE_API_KEY=AIza...\n"
"COC_API_KEY=eyJ...\n"
"OWNER_ID=ton_discord_id\n"
"DB_PATH=data/bot.db\n"
)
print("OK: .env.example")

# ══════════════════════════════════════════
# requirements.txt
# ══════════════════════════════════════════
open(f"{BASE}/requirements.txt", "w").write(
"discord.py\n"
"python-dotenv\n"
"groq\n"
"google-genai\n"
"anthropic\n"
"aiosqlite\n"
"requests\n"
"beautifulsoup4\n"
"apscheduler\n"
"httpx\n"
)
print("OK: requirements.txt")

# ══════════════════════════════════════════
# database.py
# ══════════════════════════════════════════
open(f"{BASE}/database.py", "w").write(
'import aiosqlite\n'
'import time\n'
'import os\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'DB_PATH = os.getenv("DB_PATH", "data/bot.db")\n'
'\n'
'async def init_db():\n'
'    async with aiosqlite.connect(DB_PATH) as db:\n'
'        await db.executescript("""\n'
'            CREATE TABLE IF NOT EXISTS cache (\n'
'                cache_key TEXT PRIMARY KEY,\n'
'                value TEXT,\n'
'                source TEXT,\n'
'                created INTEGER\n'
'            );\n'
'            CREATE TABLE IF NOT EXISTS logs (\n'
'                id INTEGER PRIMARY KEY AUTOINCREMENT,\n'
'                guild_id TEXT,\n'
'                user_id TEXT,\n'
'                command TEXT,\n'
'                result TEXT,\n'
'                ai_used TEXT,\n'
'                cost REAL,\n'
'                created INTEGER\n'
'            );\n'
'            CREATE TABLE IF NOT EXISTS blacklist (\n'
'                user_id TEXT PRIMARY KEY,\n'
'                reason TEXT,\n'
'                created INTEGER\n'
'            );\n'
'            CREATE TABLE IF NOT EXISTS rate_limit (\n'
'                user_id TEXT PRIMARY KEY,\n'
'                count INTEGER,\n'
'                window_start INTEGER\n'
'            );\n'
'            CREATE TABLE IF NOT EXISTS feedback (\n'
'                id INTEGER PRIMARY KEY AUTOINCREMENT,\n'
'                user_id TEXT,\n'
'                link TEXT,\n'
'                note INTEGER,\n'
'                created INTEGER\n'
'            );\n'
'        """)\n'
'        await db.commit()\n'
'\n'
'async def get_cache(key):\n'
'    try:\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute("SELECT value, created FROM cache WHERE cache_key=?", (key,)) as c:\n'
'                row = await c.fetchone()\n'
'                if row and (time.time() - row[1]) < 86400:\n'
'                    return row[0]\n'
'                if row:\n'
'                    await db.execute("DELETE FROM cache WHERE cache_key=?", (key,))\n'
'                    await db.commit()\n'
'    except Exception:\n'
'        pass\n'
'    return None\n'
'\n'
'async def set_cache(key, value, source="", hours=24):\n'
'    try:\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute(\n'
'                "INSERT OR REPLACE INTO cache (cache_key, value, source, created) VALUES (?,?,?,?)",\n'
'                (key, value, source, int(time.time()))\n'
'            )\n'
'            await db.commit()\n'
'    except Exception:\n'
'        pass\n'
'\n'
'async def is_blacklisted(user_id):\n'
'    try:\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute("SELECT 1 FROM blacklist WHERE user_id=?", (user_id,)) as c:\n'
'                return await c.fetchone() is not None\n'
'    except Exception:\n'
'        return False\n'
'\n'
'async def check_rate_limit(user_id, limit=10, window=3600):\n'
'    try:\n'
'        now = int(time.time())\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute("SELECT count, window_start FROM rate_limit WHERE user_id=?", (user_id,)) as c:\n'
'                row = await c.fetchone()\n'
'            if row:\n'
'                count, start = row\n'
'                if now - start > window:\n'
'                    await db.execute("UPDATE rate_limit SET count=1, window_start=? WHERE user_id=?", (now, user_id))\n'
'                elif count >= limit:\n'
'                    await db.commit()\n'
'                    return False\n'
'                else:\n'
'                    await db.execute("UPDATE rate_limit SET count=count+1 WHERE user_id=?", (user_id,))\n'
'            else:\n'
'                await db.execute("INSERT INTO rate_limit (user_id, count, window_start) VALUES (?,1,?)", (user_id, now))\n'
'            await db.commit()\n'
'        return True\n'
'    except Exception:\n'
'        return True\n'
'\n'
'async def log_command(guild_id, user_id, command, result, ai_used="", cost=0.0):\n'
'    try:\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute(\n'
'                "INSERT INTO logs (guild_id, user_id, command, result, ai_used, cost, created) VALUES (?,?,?,?,?,?,?)",\n'
'                (str(guild_id), str(user_id), command, result, ai_used, cost, int(time.time()))\n'
'            )\n'
'            await db.commit()\n'
'    except Exception:\n'
'        pass\n'
)
print("OK: database.py")

# ══════════════════════════════════════════
# youtube_search.py
# ══════════════════════════════════════════
open(f"{BASE}/youtube_search.py", "w").write(
'import os\n'
'import requests\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'YT_KEY = os.getenv("YOUTUBE_API_KEY", "")\n'
'\n'
'def search_youtube_coc(query, max_results=3):\n'
'    if not YT_KEY:\n'
'        return []\n'
'    try:\n'
'        r = requests.get(\n'
'            "https://www.googleapis.com/youtube/v3/search",\n'
'            params={"part": "snippet", "q": query + " Clash of Clans 2025",\n'
'                    "type": "video", "maxResults": max_results, "key": YT_KEY},\n'
'            timeout=5\n'
'        )\n'
'        results = []\n'
'        for item in r.json().get("items", []):\n'
'            results.append({\n'
'                "title": item["snippet"]["title"],\n'
'                "url": "https://youtu.be/" + item["id"]["videoId"],\n'
'                "description": item["snippet"]["description"][:400],\n'
'                "channel": item["snippet"]["channelTitle"]\n'
'            })\n'
'        return results\n'
'    except Exception as e:\n'
'        print("[YouTube]", e)\n'
'        return []\n'
'\n'
'def youtube_context(videos):\n'
'    if not videos:\n'
'        return ""\n'
'    lines = ["Informations issues de vraies videos Clash of Clans sur YouTube :"]\n'
'    for v in videos:\n'
'        lines.append("- " + v["title"] + " (" + v["channel"] + ") : " + v["description"])\n'
'    return "\\n".join(lines)\n'
)
print("OK: youtube_search.py")

# ══════════════════════════════════════════
# ai_cascade.py
# ══════════════════════════════════════════
open(f"{BASE}/ai_cascade.py", "w").write(
'from __future__ import annotations\n'
'import os, asyncio\n'
'from typing import Optional, Tuple\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'\n'
'GROQ_KEY = os.getenv("GROQ_API_KEY", "")\n'
'GEMINI_KEY = os.getenv("GEMINI_API_KEY", "")\n'
'ANTHROPIC_KEY = os.getenv("ANTHROPIC_API_KEY", "")\n'
'\n'
'COC_SYSTEM = (\n'
'    "Tu es ClashBot, expert Clash of Clans. "\n'
'    "Reponds UNIQUEMENT avec de vraies troupes, heros et batiments officiels du jeu. "\n'
'    "Troupes reelles : Barbare, Archer, Geant, Gobelin, Briseur de mur, Ballon, Sorcier, "\n'
'    "Guerisseuse, Dragon, PEKKA, Mini PEKKA, Golem, Valkyrie, Golem de lave, Witch, Bowler, "\n'
'    "Mineurs, Electro Dragon, Yeti, Dragon de glace, Super troupes. "\n'
'    "Heros officiels : Roi Barbare, Reine des Archers, Grand Faucon, Marionnettiste Royal, Champion. "\n'
'    "N invente AUCUN nom. HDV max actuel : 18. Reponds en francais, simplement et avec fun."\n'
')\n'
'\n'
'async def ask_groq(prompt: str) -> Tuple[Optional[str], str, float]:\n'
'    if not GROQ_KEY:\n'
'        return None, "groq", 0.0\n'
'    try:\n'
'        from groq import Groq\n'
'        client = Groq(api_key=GROQ_KEY)\n'
'        r = await asyncio.to_thread(lambda: client.chat.completions.create(\n'
'            messages=[{"role": "user", "content": COC_SYSTEM + "\\n\\n" + prompt}],\n'
'            model="llama-3.3-70b-versatile", max_tokens=1500))\n'
'        text = r.choices[0].message.content\n'
'        if text and len(text.strip()) > 20:\n'
'            return text.strip(), "groq-llama3", 0.0\n'
'    except Exception as e:\n'
'        print("[Groq]", e)\n'
'    return None, "groq", 0.0\n'
'\n'
'async def ask_gemini(prompt: str) -> Tuple[Optional[str], str, float]:\n'
'    if not GEMINI_KEY:\n'
'        return None, "gemini", 0.0\n'
'    try:\n'
'        from google import genai\n'
'        client = genai.Client(api_key=GEMINI_KEY)\n'
'        r = await asyncio.to_thread(lambda: client.models.generate_content(\n'
'            model="gemini-1.5-flash",\n'
'            contents=COC_SYSTEM + "\\n\\n" + prompt))\n'
'        text = r.text\n'
'        if text and len(text.strip()) > 20:\n'
'            return text.strip(), "gemini-1.5-flash", 0.0001\n'
'    except Exception as e:\n'
'        print("[Gemini]", e)\n'
'    return None, "gemini", 0.0\n'
'\n'
'async def ask_ai(prompt: str) -> Tuple[str, str, float]:\n'
'    for fn in [ask_groq, ask_gemini]:\n'
'        result, model, cost = await fn(prompt)\n'
'        if result:\n'
'            return result, model, cost\n'
'    return "Les IAs sont indisponibles. Reessaie dans quelques secondes !", "none", 0.0\n'
)
print("OK: ai_cascade.py")

# ══════════════════════════════════════════
# cogs/meta.py
# ══════════════════════════════════════════
open(f"{BASE}/cogs/meta.py", "w").write(
'import discord\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from database import log_command, is_blacklisted, check_rate_limit, get_cache, set_cache\n'
'from ai_cascade import ask_ai\n'
'from youtube_search import search_youtube_coc, youtube_context\n'
'\n'
'class Meta(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="meta", description="Meta actuelle Clash of Clans par HDV")\n'
'    @app_commands.describe(hdv="Ton niveau de Town Hall (1-18)")\n'
'    async def meta(self, interaction: discord.Interaction, hdv: int):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Tu es blackliste.", ephemeral=True)\n'
'            return\n'
'        if not await check_rate_limit(str(interaction.user.id)):\n'
'            await interaction.followup.send("Limite de commandes atteinte. Reessaie dans 1h.", ephemeral=True)\n'
'            return\n'
'        if hdv < 1 or hdv > 18:\n'
'            await interaction.followup.send("HDV invalide. Choisis entre 1 et 18.", ephemeral=True)\n'
'            return\n'
'        cache_key = "meta_" + str(hdv)\n'
'        cached = await get_cache(cache_key)\n'
'        if cached:\n'
'            embed = discord.Embed(title="Meta HDV" + str(hdv) + " (cache)", description=cached[:4000], color=0xE74C3C)\n'
'            await interaction.followup.send(embed=embed)\n'
'            return\n'
'        videos = search_youtube_coc("meta HDV" + str(hdv) + " meilleure armee attaque")\n'
'        yt_ctx = youtube_context(videos)\n'
'        prompt = (\n'
'            yt_ctx + "\\n\\n"\n'
'            + "Donne la meta 2025 pour Town Hall " + str(hdv) + " (HDV" + str(hdv) + ") en Clash of Clans.\\n"\n'
'            + "Reponds avec :\\n"\n'
'            + "1) Top 5 compositions avec noms de troupes REELS et quantites\\n"\n'
'            + "2) Tier list S/A/B/C avec win rate estime\\n"\n'
'            + "3) Heros prioritaires et leur utilisation\\n"\n'
'            + "4) Sorts recommandes\\n"\n'
'            + "5) Compositions a eviter et pourquoi\\n"\n'
'            + "Utilise uniquement les vraies troupes CoC. Sois precis et fun."\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        await set_cache(cache_key, result, source=ai_used, hours=12)\n'
'        embed = discord.Embed(\n'
'            title="Meta HDV" + str(hdv) + " Clash of Clans",\n'
'            description=result[:4000],\n'
'            color=0xE74C3C\n'
'        )\n'
'        if videos:\n'
'            links = "\\n".join(["[" + v["title"][:60] + "](" + v["url"] + ")" for v in videos[:3]])\n'
'            embed.add_field(name="Videos YouTube", value=links, inline=False)\n'
'        embed.set_footer(text="IA : " + ai_used + " | Clash of Clans 2025")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "meta", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="compo", description="Analyse complete d une composition CoC")\n'
'    @app_commands.describe(compo="Nom de la compo (ex: Lalo, Dragbat, Zap Drag)", hdv="Ton HDV (1-18)")\n'
'    async def compo(self, interaction: discord.Interaction, compo: str, hdv: int):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Tu es blackliste.", ephemeral=True)\n'
'            return\n'
'        if not await check_rate_limit(str(interaction.user.id)):\n'
'            await interaction.followup.send("Limite atteinte.", ephemeral=True)\n'
'            return\n'
'        videos = search_youtube_coc(compo + " HDV" + str(hdv) + " guide attaque")\n'
'        yt_ctx = youtube_context(videos)\n'
'        prompt = (\n'
'            yt_ctx + "\\n\\n"\n'
'            + "Analyse complete de la composition " + compo + " pour HDV" + str(hdv) + " en Clash of Clans.\\n"\n'
'            + "Reponds avec :\\n"\n'
'            + "1) Troupes exactes et quantites recommandees\\n"\n'
'            + "2) Sorts a emporter\\n"\n'
'            + "3) Ordre de deploiement etape par etape\\n"\n'
'            + "4) Quels types de bases cette compo detruit bien\\n"\n'
'            + "5) Contre-mesures defensives a surveiller\\n"\n'
'            + "6) Difficulte de maitrise : /5\\n"\n'
'            + "Utilise uniquement les vraies troupes CoC."\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title=compo + " - HDV" + str(hdv), description=result[:4000], color=0x9B59B6)\n'
'        if videos:\n'
'            links = "\\n".join(["[" + v["title"][:60] + "](" + v["url"] + ")" for v in videos[:3]])\n'
'            embed.add_field(name="Videos YouTube", value=links, inline=False)\n'
'        embed.set_footer(text="IA : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "compo", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="tierlist", description="Tier list des compositions par HDV")\n'
'    @app_commands.describe(hdv="Ton HDV (1-18)")\n'
'    async def tierlist(self, interaction: discord.Interaction, hdv: int):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Tu es blackliste.", ephemeral=True)\n'
'            return\n'
'        cache_key = "tierlist_" + str(hdv)\n'
'        cached = await get_cache(cache_key)\n'
'        if cached:\n'
'            embed = discord.Embed(title="Tier List HDV" + str(hdv), description=cached[:4000], color=0xF1C40F)\n'
'            await interaction.followup.send(embed=embed)\n'
'            return\n'
'        videos = search_youtube_coc("tier list meilleures armees HDV" + str(hdv))\n'
'        yt_ctx = youtube_context(videos)\n'
'        prompt = (\n'
'            yt_ctx + "\\n\\n"\n'
'            + "Tier list des compositions Clash of Clans pour HDV" + str(hdv) + " en 2025.\\n"\n'
'            + "Classe les vraies compos CoC en :\\n"\n'
'            + "S-Tier : Meilleures, dominent la meta\\n"\n'
'            + "A-Tier : Tres efficaces, recommandees\\n"\n'
'            + "B-Tier : Correctes, situationnelles\\n"\n'
'            + "C-Tier : A eviter sauf situation specifique\\n"\n'
'            + "Pour chaque compo : win rate estime et difficulte /5."\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        await set_cache(cache_key, result, source=ai_used, hours=12)\n'
'        embed = discord.Embed(title="Tier List HDV" + str(hdv), description=result[:4000], color=0xF1C40F)\n'
'        if videos:\n'
'            links = "\\n".join(["[" + v["title"][:60] + "](" + v["url"] + ")" for v in videos[:2]])\n'
'            embed.add_field(name="Videos YouTube", value=links, inline=False)\n'
'        embed.set_footer(text="IA : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "tierlist", "ok", ai_used, cost)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Meta(bot))\n'
)
print("OK: cogs/meta.py")

# ══════════════════════════════════════════
# cogs/guerre.py
# ══════════════════════════════════════════
open(f"{BASE}/cogs/guerre.py", "w").write(
'import discord\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from database import log_command, is_blacklisted, check_rate_limit, get_cache, set_cache\n'
'from ai_cascade import ask_ai\n'
'from youtube_search import search_youtube_coc, youtube_context\n'
'\n'
'class Guerre(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="stratguerre", description="Strategie complete pour une guerre de clan CoC")\n'
'    @app_commands.describe(taille="Taille (ex: 10v10, 15v15, 50v50)", hdv_moyen="HDV moyen de ton clan", style="Style : agressif, defensif, equilibre")\n'
'    async def stratguerre(self, interaction: discord.Interaction, taille: str, hdv_moyen: int, style: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Tu es blackliste.", ephemeral=True)\n'
'            return\n'
'        if not await check_rate_limit(str(interaction.user.id)):\n'
'            await interaction.followup.send("Limite atteinte.", ephemeral=True)\n'
'            return\n'
'        videos = search_youtube_coc("strategie guerre clan HDV" + str(hdv_moyen))\n'
'        yt_ctx = youtube_context(videos)\n'
'        prompt = (\n'
'            yt_ctx + "\\n\\n"\n'
'            + "Strategie de guerre de clan Clash of Clans : guerre " + taille\n'
'            + " avec HDV moyen " + str(hdv_moyen) + " style " + style + ".\\n"\n'
'            + "Reponds avec :\\n"\n'
'            + "1) Plan general de la guerre\\n"\n'
'            + "2) Qui attaque qui (matchups recommandes par HDV)\\n"\n'
'            + "3) Compositions recommandees avec vraies troupes CoC\\n"\n'
'            + "4) Ordre des attaques et timing\\n"\n'
'            + "5) Gestion des etoiles et priorites\\n"\n'
'            + "6) Plan B si les premières attaques echouent"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(\n'
'            title="Strategie Guerre " + taille + " - HDV" + str(hdv_moyen),\n'
'            description=result[:4000],\n'
'            color=0xE74C3C\n'
'        )\n'
'        if videos:\n'
'            links = "\\n".join(["[" + v["title"][:60] + "](" + v["url"] + ")" for v in videos[:2]])\n'
'            embed.add_field(name="Videos YouTube", value=links, inline=False)\n'
'        embed.set_footer(text="IA : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "stratguerre", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="analysebase", description="Analyser une base adverse en guerre")\n'
'    @app_commands.describe(hdv_adverse="HDV de la base adverse", description_base="Decris la base", ton_hdv="Ton HDV", ta_compo="Ta compo preferee")\n'
'    async def analysebase(self, interaction: discord.Interaction, hdv_adverse: int, description_base: str, ton_hdv: int, ta_compo: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Tu es blackliste.", ephemeral=True)\n'
'            return\n'
'        prompt = (\n'
'            "Analyse de base adverse en guerre Clash of Clans.\\n"\n'
'            + "Base adverse : HDV" + str(hdv_adverse) + " - " + description_base + "\\n"\n'
'            + "Mon profil : HDV" + str(ton_hdv) + " avec " + ta_compo + "\\n"\n'
'            + "Reponds avec :\\n"\n'
'            + "1) Points faibles de la base\\n"\n'
'            + "2) Meilleur point d entree\\n"\n'
'            + "3) Composition recommandee avec vraies troupes CoC\\n"\n'
'            + "4) Ordre de deploiement\\n"\n'
'            + "5) Pieges probables a eviter\\n"\n'
'            + "6) Probabilite de 2 etoiles et 3 etoiles"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Analyse Base HDV" + str(hdv_adverse), description=result[:4000], color=0x3498DB)\n'
'        embed.set_footer(text="IA : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "analysebase", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="cwl", description="Guide pour la Ligue de Guerre de Clans (CWL)")\n'
'    @app_commands.describe(ligue="Ta ligue (ex: Cristal, Maitre, Champion)", hdv="Ton HDV")\n'
'    async def cwl(self, interaction: discord.Interaction, ligue: str, hdv: int):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Tu es blackliste.", ephemeral=True)\n'
'            return\n'
'        videos = search_youtube_coc("CWL " + ligue + " HDV" + str(hdv) + " strategie")\n'
'        yt_ctx = youtube_context(videos)\n'
'        prompt = (\n'
'            yt_ctx + "\\n\\n"\n'
'            + "Guide CWL Clash of Clans - Ligue " + ligue + " HDV" + str(hdv) + ".\\n"\n'
'            + "1) Meta CWL actuelle pour ce HDV\\n"\n'
'            + "2) Meilleures compositions avec vraies troupes CoC\\n"\n'
'            + "3) Strategie de ligue (conservation, bonus, etoiles)\\n"\n'
'            + "4) Gestion des medailles\\n"\n'
'            + "5) Erreurs courantes a eviter"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Guide CWL " + ligue + " HDV" + str(hdv), description=result[:4000], color=0xF39C12)\n'
'        if videos:\n'
'            links = "\\n".join(["[" + v["title"][:60] + "](" + v["url"] + ")" for v in videos[:2]])\n'
'            embed.add_field(name="Videos YouTube", value=links, inline=False)\n'
'        embed.set_footer(text="IA : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "cwl", "ok", ai_used, cost)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Guerre(bot))\n'
)
print("OK: cogs/guerre.py")

# ══════════════════════════════════════════
# cogs/coach.py
# ══════════════════════════════════════════
open(f"{BASE}/cogs/coach.py", "w").write(
'import discord\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from database import log_command, is_blacklisted, check_rate_limit\n'
'from ai_cascade import ask_ai\n'
'from youtube_search import search_youtube_coc, youtube_context\n'
'\n'
'class Coach(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="coach", description="Coaching personnalise Clash of Clans")\n'
'    @app_commands.describe(hdv="Ton HDV", compo="Ta composition principale", probleme="Ton probleme")\n'
'    async def coach(self, interaction: discord.Interaction, hdv: int, compo: str, probleme: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Tu es blackliste.", ephemeral=True)\n'
'            return\n'
'        if not await check_rate_limit(str(interaction.user.id)):\n'
'            await interaction.followup.send("Limite atteinte.", ephemeral=True)\n'
'            return\n'
'        videos = search_youtube_coc(compo + " HDV" + str(hdv) + " tutoriel erreurs")\n'
'        yt_ctx = youtube_context(videos)\n'
'        prompt = (\n'
'            yt_ctx + "\\n\\n"\n'
'            + "Coaching Clash of Clans personnalise.\\n"\n'
'            + "Joueur : HDV" + str(hdv) + " | Compo principale : " + compo + "\\n"\n'
'            + "Probleme decrit : " + probleme + "\\n"\n'
'            + "Reponds avec :\\n"\n'
'            + "1) Diagnostic du probleme\\n"\n'
'            + "2) Exercices pratiques specifiques a faire\\n"\n'
'            + "3) Checklist avant chaque attaque\\n"\n'
'            + "4) Erreurs classiques avec " + compo + " et comment les eviter\\n"\n'
'            + "5) Plan d entrainement sur 7 jours\\n"\n'
'            + "6) Note actuelle estimee /10 et objectif atteignable"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(\n'
'            title="Coaching " + compo + " - HDV" + str(hdv),\n'
'            description=result[:4000],\n'
'            color=0x8E44AD\n'
'        )\n'
'        if videos:\n'
'            links = "\\n".join(["[" + v["title"][:60] + "](" + v["url"] + ")" for v in videos[:2]])\n'
'            embed.add_field(name="Videos YouTube", value=links, inline=False)\n'
'        embed.set_footer(text="IA : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "coach", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="progression", description="Plan de progression Clash of Clans")\n'
'    @app_commands.describe(hdv="Ton HDV actuel", objectif="Ton objectif (ex: HDV15, Legend League)")\n'
'    async def progression(self, interaction: discord.Interaction, hdv: int, objectif: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Tu es blackliste.", ephemeral=True)\n'
'            return\n'
'        prompt = (\n'
'            "Plan de progression Clash of Clans.\\n"\n'
'            + "Joueur : HDV" + str(hdv) + " | Objectif : " + objectif + "\\n"\n'
'            + "Reponds avec :\\n"\n'
'            + "1) Top 5 upgrades prioritaires a faire MAINTENANT\\n"\n'
'            + "2) Ordre optimal de progression\\n"\n'
'            + "3) Estimation du temps selon rythme normal de jeu\\n"\n'
'            + "4) Ressources a farmer en priorite\\n"\n'
'            + "5) Conseils pour progresser plus vite"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(\n'
'            title="Progression HDV" + str(hdv) + " vers " + objectif,\n'
'            description=result[:4000],\n'
'            color=0x27AE60\n'
'        )\n'
'        embed.set_footer(text="IA : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "progression", "ok", ai_used, cost)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Coach(bot))\n'
)
print("OK: cogs/coach.py")

# ══════════════════════════════════════════
# cogs/admin.py
# ══════════════════════════════════════════
open(f"{BASE}/cogs/admin.py", "w").write(
'import discord\n'
'import os\n'
'import time\n'
'import aiosqlite\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'OWNER_ID = int(os.getenv("OWNER_ID", "0"))\n'
'DB_PATH = os.getenv("DB_PATH", "data/bot.db")\n'
'\n'
'class Admin(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="logs", description="[ADMIN] Voir les derniers logs")\n'
'    async def logs(self, interaction: discord.Interaction):\n'
'        if interaction.user.id != OWNER_ID:\n'
'            await interaction.response.send_message("Acces refuse.", ephemeral=True)\n'
'            return\n'
'        await interaction.response.defer(ephemeral=True)\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute("SELECT user_id, command, result, ai_used, created FROM logs ORDER BY created DESC LIMIT 20") as c:\n'
'                rows = await c.fetchall()\n'
'        if not rows:\n'
'            await interaction.followup.send("Aucun log.", ephemeral=True)\n'
'            return\n'
'        lines = ["Derniers logs :"]\n'
'        for r in rows:\n'
'            t = time.strftime("%H:%M", time.localtime(r[4]))\n'
'            lines.append(t + " | " + str(r[0])[:8] + " | " + r[1] + " | " + r[2] + " | " + r[3])\n'
'        await interaction.followup.send("```\\n" + "\\n".join(lines) + "\\n```", ephemeral=True)\n'
'\n'
'    @app_commands.command(name="stats", description="[ADMIN] Statistiques du bot")\n'
'    async def stats(self, interaction: discord.Interaction):\n'
'        if interaction.user.id != OWNER_ID:\n'
'            await interaction.response.send_message("Acces refuse.", ephemeral=True)\n'
'            return\n'
'        await interaction.response.defer(ephemeral=True)\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute("SELECT COUNT(*) FROM logs") as c:\n'
'                total = (await c.fetchone())[0]\n'
'            async with db.execute("SELECT COUNT(*) FROM blacklist") as c:\n'
'                blacklisted = (await c.fetchone())[0]\n'
'            async with db.execute("SELECT COUNT(*) FROM cache") as c:\n'
'                cached = (await c.fetchone())[0]\n'
'        guilds = len(self.bot.guilds)\n'
'        embed = discord.Embed(title="Stats du Bot CoC", color=0x2ECC71)\n'
'        embed.add_field(name="Serveurs", value=str(guilds), inline=True)\n'
'        embed.add_field(name="Commandes totales", value=str(total), inline=True)\n'
'        embed.add_field(name="Blacklistes", value=str(blacklisted), inline=True)\n'
'        embed.add_field(name="Entrees en cache", value=str(cached), inline=True)\n'
'        await interaction.followup.send(embed=embed, ephemeral=True)\n'
'\n'
'    @app_commands.command(name="blacklist", description="[ADMIN] Blacklister un utilisateur")\n'
'    @app_commands.describe(user_id="ID Discord de l utilisateur", raison="Raison")\n'
'    async def blacklist_user(self, interaction: discord.Interaction, user_id: str, raison: str):\n'
'        if interaction.user.id != OWNER_ID:\n'
'            await interaction.response.send_message("Acces refuse.", ephemeral=True)\n'
'            return\n'
'        await interaction.response.defer(ephemeral=True)\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute("INSERT OR REPLACE INTO blacklist (user_id, reason, created) VALUES (?,?,?)", (user_id, raison, int(time.time())))\n'
'            await db.commit()\n'
'        await interaction.followup.send("Utilisateur " + user_id + " blackliste.", ephemeral=True)\n'
'\n'
'    @app_commands.command(name="clearcache", description="[ADMIN] Vider le cache du bot")\n'
'    async def clearcache(self, interaction: discord.Interaction):\n'
'        if interaction.user.id != OWNER_ID:\n'
'            await interaction.response.send_message("Acces refuse.", ephemeral=True)\n'
'            return\n'
'        await interaction.response.defer(ephemeral=True)\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute("DELETE FROM cache")\n'
'            await db.commit()\n'
'        await interaction.followup.send("Cache vide avec succes !", ephemeral=True)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Admin(bot))\n'
)
print("OK: cogs/admin.py")

# ══════════════════════════════════════════
# cogs/info.py
# ══════════════════════════════════════════
open(f"{BASE}/cogs/info.py", "w").write(
'import discord\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from database import log_command, is_blacklisted, check_rate_limit, get_cache, set_cache\n'
'from ai_cascade import ask_ai\n'
'from youtube_search import search_youtube_coc, youtube_context\n'
'import requests\n'
'\n'
'COC_API = None\n'
'\n'
'class Info(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="aide", description="Que faire maintenant dans CoC ?")\n'
'    @app_commands.describe(hdv="Ton HDV", situation="Decris ta situation actuelle")\n'
'    async def aide(self, interaction: discord.Interaction, hdv: int, situation: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Tu es blackliste.", ephemeral=True)\n'
'            return\n'
'        prompt = (\n'
'            "Conseil Clash of Clans personnalise.\\n"\n'
'            + "HDV" + str(hdv) + " | Situation : " + situation + "\\n"\n'
'            + "Que devrait faire ce joueur MAINTENANT ?\\n"\n'
'            + "Reponds de facon simple, directe et actionnable en 5 points maximum."\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Que faire ? HDV" + str(hdv), description=result[:4000], color=0x3498DB)\n'
'        embed.set_footer(text="IA : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "aide", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="patch", description="Dernieres notes de mise a jour CoC")\n'
'    async def patch(self, interaction: discord.Interaction):\n'
'        await interaction.response.defer()\n'
'        cache_key = "patch_notes"\n'
'        cached = await get_cache(cache_key)\n'
'        if cached:\n'
'            embed = discord.Embed(title="Patch Notes CoC", description=cached[:4000], color=0x1ABC9C)\n'
'            await interaction.followup.send(embed=embed)\n'
'            return\n'
'        videos = search_youtube_coc("clash of clans update patch notes 2025")\n'
'        yt_ctx = youtube_context(videos)\n'
'        prompt = (\n'
'            yt_ctx + "\\n\\n"\n'
'            + "Resume les dernieres mises a jour de Clash of Clans en 2025.\\n"\n'
'            + "1) Quoi de neuf (nouveaux batiments, troupes, heros)\\n"\n'
'            + "2) Balance changes importants\\n"\n'
'            + "3) Impact sur la meta actuelle\\n"\n'
'            + "4) Ce que tu dois adapter dans ta strategie"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        await set_cache(cache_key, result, source=ai_used, hours=6)\n'
'        embed = discord.Embed(title="Patch Notes CoC 2025", description=result[:4000], color=0x1ABC9C)\n'
'        if videos:\n'
'            links = "\\n".join(["[" + v["title"][:60] + "](" + v["url"] + ")" for v in videos[:2]])\n'
'            embed.add_field(name="Videos YouTube", value=links, inline=False)\n'
'        embed.set_footer(text="IA : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "patch", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="quiz", description="Quiz Clash of Clans - Teste tes connaissances !")\n'
'    async def quiz(self, interaction: discord.Interaction):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Tu es blackliste.", ephemeral=True)\n'
'            return\n'
'        prompt = (\n'
'            "Genere 5 questions de quiz Clash of Clans avec reponses.\\n"\n'
'            + "Questions variees : troupes, batiments, heros, histoire du jeu, strategies.\\n"\n'
'            + "Format : Q1: [question] | R: [reponse]\\n"\n'
'            + "Utilise uniquement des elements reels de CoC."\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Quiz Clash of Clans", description=result[:4000], color=0xE67E22)\n'
'        embed.set_footer(text="IA : " + ai_used + " | Les reponses sont revelees dans le meme message !")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "quiz", "ok", ai_used, cost)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Info(bot))\n'
)
print("OK: cogs/info.py")

# ══════════════════════════════════════════
# bot.py principal
# ══════════════════════════════════════════
open(f"{BASE}/bot.py", "w").write(
'import discord\n'
'import asyncio\n'
'import os\n'
'from discord.ext import commands\n'
'from dotenv import load_dotenv\n'
'from database import init_db\n'
'load_dotenv()\n'
'\n'
'TOKEN = os.getenv("DISCORD_TOKEN", "")\n'
'OWNER_ID = int(os.getenv("OWNER_ID", "0"))\n'
'\n'
'COGS = ["cogs.meta", "cogs.guerre", "cogs.coach", "cogs.info", "cogs.admin"]\n'
'\n'
'intents = discord.Intents.default()\n'
'intents.message_content = True\n'
'bot = commands.Bot(command_prefix="!", intents=intents)\n'
'\n'
'@bot.event\n'
'async def on_ready():\n'
'    print("Connecte : " + str(bot.user))\n'
'    print("Serveurs : " + str(len(bot.guilds)))\n'
'    try:\n'
'        synced = await bot.tree.sync()\n'
'        print("Commandes synchro : " + str(len(synced)))\n'
'    except Exception as e:\n'
'        print("Erreur sync : " + str(e))\n'
'\n'
'async def main():\n'
'    await init_db()\n'
'    for cog in COGS:\n'
'        try:\n'
'            await bot.load_extension(cog)\n'
'            print("Cog OK : " + cog)\n'
'        except Exception as e:\n'
'            print("Erreur cog " + cog + " : " + str(e))\n'
'    await bot.start(TOKEN)\n'
'\n'
'asyncio.run(main())\n'
)
print("OK: bot.py")

print("\n" + "="*50)
print("BOT COC CONSTRUIT AVEC SUCCES !")
print("="*50)
print("Lance maintenant : python3 bot.py")
print("Commandes disponibles :")
print("  /meta [hdv]")
print("  /compo [compo] [hdv]")
print("  /tierlist [hdv]")
print("  /stratguerre [taille] [hdv] [style]")
print("  /analysebase [hdv] [description] [mon_hdv] [compo]")
print("  /cwl [ligue] [hdv]")
print("  /coach [hdv] [compo] [probleme]")
print("  /progression [hdv] [objectif]")
print("  /aide [hdv] [situation]")
print("  /patch")
print("  /quiz")
print("  /logs /stats /blacklist /clearcache [ADMIN]")
