"""
REBUILD COMPLET v3 - Bot CoC
- FindThisBase + ClashChamps + cocbases.com scraping
- Roboflow → Gemini Vision → cascade IA
- Boutons interactifs Discord
- Toutes les commandes du tableau
Lance : python3 rebuild_v3.py
"""
import os
BASE = os.path.expanduser("~/coc-bot")
os.makedirs(f"{BASE}/cogs", exist_ok=True)
os.makedirs(f"{BASE}/data", exist_ok=True)

# ══════════════════════════════════════════
# sources.py — YouTube + Twitch + CCN + FTB + cocbases
# ══════════════════════════════════════════
open(f"{BASE}/sources.py", "w").write(
'import os, requests, asyncio\n'
'from bs4 import BeautifulSoup\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'YT_KEY = os.getenv("YOUTUBE_API_KEY", "")\n'
'HEADERS = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"}\n'
'\n'
'# ── YouTube ──────────────────────────────\n'
'def search_youtube(query, max_results=3, order="date"):\n'
'    if not YT_KEY:\n'
'        return []\n'
'    try:\n'
'        r = requests.get(\n'
'            "https://www.googleapis.com/youtube/v3/search",\n'
'            params={"part":"snippet","q":query+" Clash of Clans 2025",\n'
'                    "type":"video","maxResults":max_results,"order":order,"key":YT_KEY},\n'
'            timeout=5\n'
'        )\n'
'        results = []\n'
'        for item in r.json().get("items",[]):\n'
'            results.append({\n'
'                "source":"YouTube","badge":"",\n'
'                "title":item["snippet"]["title"],\n'
'                "url":"https://youtu.be/"+item["id"]["videoId"],\n'
'                "desc":item["snippet"]["description"][:300],\n'
'                "channel":item["snippet"]["channelTitle"]\n'
'            })\n'
'        return results\n'
'    except Exception as e:\n'
'        print("[YouTube]",e)\n'
'        return []\n'
'\n'
'# ── Twitch ───────────────────────────────\n'
'def search_twitch(query):\n'
'    try:\n'
'        r = requests.get(\n'
'            "https://api.twitch.tv/helix/search/channels",\n'
'            params={"query":query+" clash clans","live_only":"true","first":3},\n'
'            headers={"Client-ID":"kimne78kx3ncx6brgo4mv6wki5h1ko",\n'
'                     "Authorization":"Bearer "+os.getenv("TWITCH_TOKEN","invalid")},\n'
'            timeout=5\n'
'        )\n'
'        results = []\n'
'        for ch in r.json().get("data",[]):\n'
'            results.append({\n'
'                "source":"Twitch","badge":"🟣",\n'
'                "title":ch.get("title",ch.get("display_name","")),\n'
'                "url":"https://twitch.tv/"+ch.get("broadcaster_login",""),\n'
'                "desc":"Stream live : "+ch.get("game_name","Clash of Clans"),\n'
'                "channel":ch.get("display_name","")\n'
'            })\n'
'        return results\n'
'    except Exception as e:\n'
'        print("[Twitch]",e)\n'
'        return []\n'
'\n'
'# ── ClashChamps ──────────────────────────\n'
'def search_clashchamps(query):\n'
'    try:\n'
'        r = requests.get(\n'
'            "https://clashchamps.com/?s="+query.replace(" ","+"),\n'
'            headers=HEADERS, timeout=5\n'
'        )\n'
'        soup = BeautifulSoup(r.text,"html.parser")\n'
'        results = []\n'
'        for art in soup.select("article")[:3]:\n'
'            a = art.select_one("h2 a") or art.select_one("h3 a")\n'
'            p = art.select_one("p")\n'
'            if a:\n'
'                results.append({\n'
'                    "source":"ClashChamps","badge":"⭐",\n'
'                    "title":a.text.strip(),\n'
'                    "url":a.get("href",""),\n'
'                    "desc":(p.text.strip()[:200] if p else "Guide pro CoC"),\n'
'                    "channel":"ClashChamps"\n'
'                })\n'
'        return results\n'
'    except Exception as e:\n'
'        print("[CCN]",e)\n'
'        return []\n'
'\n'
'# ── FindThisBase ─────────────────────────\n'
'def search_findthisbase(hdv, base_type=""):\n'
'    try:\n'
'        params = {"th":str(hdv)}\n'
'        if base_type:\n'
'            params["type"] = base_type\n'
'        r = requests.get("https://findthisbase.com/",params=params,headers=HEADERS,timeout=5)\n'
'        soup = BeautifulSoup(r.text,"html.parser")\n'
'        results = []\n'
'        # Cherche les bases listees\n'
'        for card in soup.select(".base-card, .base-item, article, .card")[:5]:\n'
'            link = card.select_one("a")\n'
'            img = card.select_one("img")\n'
'            title_el = card.select_one("h2,h3,h4,.title")\n'
'            if link:\n'
'                url = link.get("href","")\n'
'                if url and not url.startswith("http"):\n'
'                    url = "https://findthisbase.com" + url\n'
'                title = title_el.text.strip() if title_el else "Base HDV"+str(hdv)\n'
'                results.append({\n'
'                    "source":"FindThisBase","badge":"🔍",\n'
'                    "title":title,\n'
'                    "url":url,\n'
'                    "desc":"Base HDV"+str(hdv)+" sur FindThisBase",\n'
'                    "channel":"FindThisBase"\n'
'                })\n'
'        # Fallback si pas de resultats\n'
'        if not results:\n'
'            results.append({\n'
'                "source":"FindThisBase","badge":"🔍",\n'
'                "title":"Bases HDV"+str(hdv)+" sur FindThisBase",\n'
'                "url":"https://findthisbase.com/?th="+str(hdv),\n'
'                "desc":"Bibliotheque de bases HDV"+str(hdv),\n'
'                "channel":"FindThisBase"\n'
'            })\n'
'        return results\n'
'    except Exception as e:\n'
'        print("[FTB]",e)\n'
'        return [{"source":"FindThisBase","badge":"🔍",\n'
'                 "title":"Bases HDV"+str(hdv)+" FindThisBase",\n'
'                 "url":"https://findthisbase.com/?th="+str(hdv),\n'
'                 "desc":"Voir les bases","channel":"FindThisBase"}]\n'
'\n'
'# ── CocBases ────────────────────────────\n'
'def search_cocbases(hdv, base_type=""):\n'
'    try:\n'
'        url = "https://cocbases.com/th"+str(hdv)+"-bases/"\n'
'        if base_type:\n'
'            url = "https://cocbases.com/th"+str(hdv)+"-"+base_type+"-bases/"\n'
'        r = requests.get(url, headers=HEADERS, timeout=5)\n'
'        soup = BeautifulSoup(r.text,"html.parser")\n'
'        results = []\n'
'        for a in soup.select("a.base-link, .base-card a, article a")[:3]:\n'
'            href = a.get("href","")\n'
'            if href and "cocbases.com" in href:\n'
'                results.append({\n'
'                    "source":"CocBases","badge":"🏰",\n'
'                    "title":a.text.strip() or "Base HDV"+str(hdv),\n'
'                    "url":href,\n'
'                    "desc":"Base HDV"+str(hdv)+" sur CocBases",\n'
'                    "channel":"CocBases"\n'
'                })\n'
'        if not results:\n'
'            results.append({\n'
'                "source":"CocBases","badge":"🏰",\n'
'                "title":"Bases HDV"+str(hdv)+" CocBases",\n'
'                "url":"https://cocbases.com/th"+str(hdv)+"-bases/",\n'
'                "desc":"Bibliotheque CocBases","channel":"CocBases"\n'
'            })\n'
'        return results\n'
'    except Exception as e:\n'
'        print("[CocBases]",e)\n'
'        return []\n'
'\n'
'# ── Aggregateur principal ────────────────\n'
'async def get_all_sources(query, hdv=None, include_bases=False, base_type=""):\n'
'    results = []\n'
'    q = ("HDV"+str(hdv)+" " if hdv else "")+query\n'
'    # YouTube en priorite\n'
'    yt = await asyncio.to_thread(search_youtube, q, 3)\n'
'    results += yt\n'
'    # Twitch\n'
'    tw = await asyncio.to_thread(search_twitch, query)\n'
'    results += tw\n'
'    # ClashChamps\n'
'    ccn = await asyncio.to_thread(search_clashchamps, q)\n'
'    results += ccn\n'
'    # FindThisBase et CocBases si demandes\n'
'    if include_bases and hdv:\n'
'        ftb = await asyncio.to_thread(search_findthisbase, hdv, base_type)\n'
'        results += ftb\n'
'        coc = await asyncio.to_thread(search_cocbases, hdv, base_type)\n'
'        results += coc\n'
'    return results\n'
'\n'
'def format_sources(results):\n'
'    if not results:\n'
'        return ""\n'
'    icons = {"YouTube":"▶️","Twitch":"🟣","ClashChamps":"⭐","FindThisBase":"🔍","CocBases":"🏰"}\n'
'    lines = ["Sources recentes Clash of Clans :"]\n'
'    for r in results[:6]:\n'
'        icon = icons.get(r["source"],"🔗")\n'
'        lines.append(icon+" ["+r["source"]+"] "+r["title"]+" : "+r["desc"][:150])\n'
'    return "\\n".join(lines)\n'
'\n'
'def format_links(results):\n'
'    if not results:\n'
'        return ""\n'
'    icons = {"YouTube":"▶️","Twitch":"🟣","ClashChamps":"⭐","FindThisBase":"🔍","CocBases":"🏰"}\n'
'    lines = []\n'
'    for r in results[:5]:\n'
'        if r.get("url"):\n'
'            icon = icons.get(r["source"],"🔗")\n'
'            badge = " ⭐ Pro" if r["source"]=="ClashChamps" else ""\n'
'            lines.append(icon+" ["+r["title"][:45]+badge+"]("+r["url"]+")")\n'
'    return "\\n".join(lines)\n'
)
print("OK: sources.py")

# ══════════════════════════════════════════
# vision.py — Roboflow → Gemini Vision
# ══════════════════════════════════════════
open(f"{BASE}/vision.py", "w").write(
'import os, asyncio, base64, json, re\n'
'import requests as req\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'GEMINI_KEY = os.getenv("GEMINI_API_KEY","")\n'
'ROBOFLOW_KEY = os.getenv("ROBOFLOW_API_KEY","")\n'
'\n'
'async def detect_with_roboflow(image_url):\n'
'    if not ROBOFLOW_KEY:\n'
'        return None\n'
'    try:\n'
'        r = req.post(\n'
'            "https://detect.roboflow.com/clash-of-clans-vop4y/4",\n'
'            params={"api_key":ROBOFLOW_KEY,"image":image_url},\n'
'            timeout=10\n'
'        )\n'
'        data = r.json()\n'
'        predictions = data.get("predictions",[])\n'
'        if predictions:\n'
'            best = max(predictions, key=lambda x: x.get("confidence",0))\n'
'            confidence = best.get("confidence",0)*100\n'
'            label = best.get("class","").lower()\n'
'            hdv_match = re.search(r"th(\\d{1,2})", label)\n'
'            hdv = int(hdv_match.group(1)) if hdv_match else 0\n'
'            return {"hdv":hdv,"confidence":confidence,"label":label,"source":"roboflow"}\n'
'    except Exception as e:\n'
'        print("[Roboflow]",e)\n'
'    return None\n'
'\n'
'async def detect_with_gemini(image_url, prompt_extra=""):\n'
'    if not GEMINI_KEY:\n'
'        return None\n'
'    try:\n'
'        img_data = req.get(image_url, timeout=10).content\n'
'        content_type = "image/png"\n'
'        from google import genai\n'
'        from google.genai import types\n'
'        client = genai.Client(api_key=GEMINI_KEY)\n'
'        prompt = (\n'
'            "Tu es un expert Clash of Clans. Analyse ce screenshot.\\n"\n'
'            + prompt_extra\n'
'            + "Reponds UNIQUEMENT en JSON valide sans markdown :\\n"\n'
'            + \'{"hdv":X,"type_base":"diamond|box|ring|anti3|hybrid",\'\n'
'            + \'"style":"anti_air|anti_ground|anti_3stars|anti_2stars|farming",\'\n'
'            + \'"description":"description courte",\'\n'
'            + \'"points_forts":"forces de la base",\'\n'
'            + \'"points_faibles":"faiblesses de la base",\'\n'
'            + \'"confidence":X}\'\n'
'        )\n'
'        response = await asyncio.to_thread(lambda: client.models.generate_content(\n'
'            model="gemini-1.5-flash",\n'
'            contents=[\n'
'                types.Part.from_bytes(data=img_data, mime_type=content_type),\n'
'                types.Part.from_text(text=prompt)\n'
'            ]\n'
'        ))\n'
'        text = response.text.strip()\n'
'        match = re.search(r"\\{.*\\}", text, re.DOTALL)\n'
'        if match:\n'
'            return json.loads(match.group())\n'
'    except Exception as e:\n'
'        print("[GeminiVision]",e)\n'
'    return None\n'
'\n'
'async def analyze_base_image(image_url):\n'
'    default = {"hdv":0,"type_base":"unknown","style":"unknown","description":"Analyse impossible","points_forts":"","points_faibles":"","confidence":0}\n'
'    # 1. Roboflow en premier\n'
'    robo = await detect_with_roboflow(image_url)\n'
'    if robo and robo.get("confidence",0) >= 80:\n'
'        # Confiance suffisante avec Roboflow\n'
'        result = default.copy()\n'
'        result.update({"hdv":robo["hdv"],"confidence":robo["confidence"],"source":"roboflow"})\n'
'        # Enrichir avec Gemini pour les details\n'
'        gemini = await detect_with_gemini(image_url, "Roboflow a detecte TH"+str(robo["hdv"])+". Confirme et donne les details. ")\n'
'        if gemini:\n'
'            result.update(gemini)\n'
'        return result\n'
'    # 2. Gemini Vision si Roboflow insuffisant\n'
'    gemini = await detect_with_gemini(image_url)\n'
'    if gemini:\n'
'        return gemini\n'
'    return default\n'
'\n'
'async def analyze_attack_image(image_url):\n'
'    default = {"compo":"inconnue","etoiles":0,"pourcentage":0,"erreurs":[],"points_positifs":[],"note":5,"description":"Analyse impossible"}\n'
'    if not GEMINI_KEY:\n'
'        return default\n'
'    try:\n'
'        img_data = req.get(image_url, timeout=10).content\n'
'        from google import genai\n'
'        from google.genai import types\n'
'        client = genai.Client(api_key=GEMINI_KEY)\n'
'        prompt = (\n'
'            "Analyse ce replay d attaque Clash of Clans.\\n"\n'
'            + "Reponds UNIQUEMENT en JSON valide :\\n"\n'
'            + \'{"compo":"composition detectee","etoiles":X,"pourcentage":X,\'\n'
'            + \'"erreurs":["erreur1","erreur2"],"points_positifs":["point1"],\'\n'
'            + \'"note":X,"description":"description de l attaque"}\'\n'
'        )\n'
'        response = await asyncio.to_thread(lambda: client.models.generate_content(\n'
'            model="gemini-1.5-flash",\n'
'            contents=[\n'
'                types.Part.from_bytes(data=img_data, mime_type="image/png"),\n'
'                types.Part.from_text(text=prompt)\n'
'            ]\n'
'        ))\n'
'        import re, json\n'
'        match = re.search(r"\\{.*\\}", response.text.strip(), re.DOTALL)\n'
'        if match:\n'
'            return json.loads(match.group())\n'
'    except Exception as e:\n'
'        print("[VisionAttack]",e)\n'
'    return default\n'
)
print("OK: vision.py")

# ══════════════════════════════════════════
# ai_cascade.py
# ══════════════════════════════════════════
open(f"{BASE}/ai_cascade.py", "w").write(
'from __future__ import annotations\n'
'import os, asyncio\n'
'from typing import Optional, Tuple\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'GROQ_KEY = os.getenv("GROQ_API_KEY","")\n'
'GEMINI_KEY = os.getenv("GEMINI_API_KEY","")\n'
'\n'
'COC_SYSTEM = (\n'
'    "Tu es ClashBot, expert Clash of Clans 2025. "\n'
'    "Reponds UNIQUEMENT avec de vraies troupes officielles CoC : "\n'
'    "Barbare, Archer, Geant, Gobelin, Briseur de mur, Ballon, Sorcier, Guerisseuse, "\n'
'    "Dragon, PEKKA, Mini PEKKA, Golem, Valkyrie, Golem de lave, Witch, Bowler, Mineurs, "\n'
'    "Electro Dragon, Yeti, Dragon de glace, Cavalier Racine, Super troupes. "\n'
'    "Heros officiels : Roi Barbare, Reine des Archers, Grand Faucon, Marionnettiste Royal, Champion. "\n'
'    "N invente AUCUN nom. HDV max : 18. Reponds en francais, simplement et avec fun. "\n'
'    "Donne des quantites precises de troupes adaptees a la capacite d armee du HDV concerne."\n'
')\n'
'\n'
'async def ask_groq(prompt: str) -> Tuple[Optional[str], str, float]:\n'
'    if not GROQ_KEY:\n'
'        return None, "groq", 0.0\n'
'    try:\n'
'        from groq import Groq\n'
'        client = Groq(api_key=GROQ_KEY)\n'
'        r = await asyncio.to_thread(lambda: client.chat.completions.create(\n'
'            messages=[{"role":"user","content":COC_SYSTEM+"\\n\\n"+prompt}],\n'
'            model="llama-3.3-70b-versatile", max_tokens=1500))\n'
'        text = r.choices[0].message.content\n'
'        if text and len(text.strip()) > 20:\n'
'            return text.strip(), "groq-llama3", 0.0\n'
'    except Exception as e:\n'
'        print("[Groq]",e)\n'
'    return None, "groq", 0.0\n'
'\n'
'async def ask_gemini(prompt: str) -> Tuple[Optional[str], str, float]:\n'
'    if not GEMINI_KEY:\n'
'        return None, "gemini", 0.0\n'
'    try:\n'
'        from google import genai\n'
'        client = genai.Client(api_key=GEMINI_KEY)\n'
'        r = await asyncio.to_thread(lambda: client.models.generate_content(\n'
'            model="gemini-1.5-flash", contents=COC_SYSTEM+"\\n\\n"+prompt))\n'
'        text = r.text\n'
'        if text and len(text.strip()) > 20:\n'
'            return text.strip(), "gemini-1.5-flash", 0.0001\n'
'    except Exception as e:\n'
'        print("[Gemini]",e)\n'
'    return None, "gemini", 0.0\n'
'\n'
'async def ask_ai(prompt: str) -> Tuple[str, str, float]:\n'
'    for fn in [ask_groq, ask_gemini]:\n'
'        result, model, cost = await fn(prompt)\n'
'        if result:\n'
'            return result, model, cost\n'
'    return "IAs indisponibles, reessaie dans quelques secondes !", "none", 0.0\n'
)
print("OK: ai_cascade.py")

# ══════════════════════════════════════════
# cogs/bases.py — commandes avec screenshot
# ══════════════════════════════════════════
open(f"{BASE}/cogs/bases.py", "w").write(
'import discord, os, time, aiosqlite\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from database import log_command, is_blacklisted, check_rate_limit\n'
'from ai_cascade import ask_ai\n'
'from sources import get_all_sources, format_sources, format_links\n'
'from vision import analyze_base_image, analyze_attack_image\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'DB_PATH = os.getenv("DB_PATH","data/bot.db")\n'
'\n'
'class Bases(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="analysebase", description="Screenshot base → IA detecte + replays YouTube/Twitch/FTB")\n'
'    @app_commands.describe(screenshot="Screenshot de la base", ton_hdv="Ton HDV pour attaquer")\n'
'    async def analysebase(self, interaction: discord.Interaction, screenshot: discord.Attachment, ton_hdv: int):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        msg = await interaction.followup.send("🔍 Analyse du screenshot en cours (Roboflow → Gemini)...")\n'
'        vision = await analyze_base_image(screenshot.url)\n'
'        hdv = vision.get("hdv",0)\n'
'        type_base = vision.get("type_base","unknown")\n'
'        style = vision.get("style","unknown")\n'
'        desc = vision.get("description","")\n'
'        points_faibles = vision.get("points_faibles","")\n'
'        confidence = vision.get("confidence",0)\n'
'        hdv_str = str(hdv) if hdv else "?"\n'
'        # Sources YouTube + Twitch + FTB + CocBases\n'
'        sources = await get_all_sources(\n'
'            "attaque 3 etoiles "+type_base+" replay",\n'
'            hdv if hdv else None, include_bases=True, base_type=type_base\n'
'        )\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            "ANALYSE BASE DETECTEE (IA Vision) :\\n"\n'
'            "HDV : "+hdv_str+" | Type : "+type_base+" | Style : "+style+"\\n"\n'
'            "Description : "+desc+"\\n"\n'
'            "Points faibles : "+points_faibles+"\\n\\n"\n'
'            +ctx+"\\n\\n"\n'
'            "Mon HDV attaquant : "+str(ton_hdv)+"\\n"\n'
'            "1) Meilleure compo avec vraies troupes CoC et quantites exactes\\n"\n'
'            "2) Point d entree ideal pour ce type "+type_base+"\\n"\n'
'            "3) Sorts recommandes\\n"\n'
'            "4) Ordre de deploiement etape par etape\\n"\n'
'            "5) Pieges probables sur ce type de base\\n"\n'
'            "6) Probabilite 2 etoiles et 3 etoiles"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        color = 0x2ECC71 if confidence >= 80 else 0xE67E22\n'
'        embed = discord.Embed(\n'
'            title="Analyse Base HDV"+hdv_str+" - "+type_base,\n'
'            description=result[:4000], color=color\n'
'        )\n'
'        embed.add_field(name="HDV detecte", value=hdv_str, inline=True)\n'
'        embed.add_field(name="Type", value=type_base, inline=True)\n'
'        embed.add_field(name="Confiance", value=str(round(confidence))+"%", inline=True)\n'
'        if desc:\n'
'            embed.add_field(name="Description IA", value=desc[:200], inline=False)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Replays YouTube / Twitch / FTB / CCN ⭐", value=links, inline=False)\n'
'        embed.set_thumbnail(url=screenshot.url)\n'
'        src_label = "Roboflow+Gemini" if confidence >= 80 else "Gemini Vision"\n'
'        embed.set_footer(text="Vision : "+src_label+" | Strategie : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "analysebase", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="attack", description="Screenshot base adverse → strategie complete + replays")\n'
'    @app_commands.describe(screenshot="Screenshot de la base adverse", ton_hdv="Ton HDV")\n'
'    async def attack(self, interaction: discord.Interaction, screenshot: discord.Attachment, ton_hdv: int):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        await interaction.followup.send("🔍 Analyse en cours...")\n'
'        vision = await analyze_base_image(screenshot.url)\n'
'        hdv = vision.get("hdv",0)\n'
'        type_base = vision.get("type_base","unknown")\n'
'        points_faibles = vision.get("points_faibles","")\n'
'        hdv_str = str(hdv) if hdv else "?"\n'
'        sources = await get_all_sources(\n'
'            "attaque 3 etoiles "+type_base+" HDV"+hdv_str+" replay guide",\n'
'            hdv if hdv else None, include_bases=False\n'
'        )\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            "Strategie attaque Clash of Clans.\\n"\n'
'            "Base : HDV"+hdv_str+" type "+type_base+"\\n"\n'
'            "Points faibles : "+points_faibles+"\\n\\n"\n'
'            +ctx+"\\n\\n"\n'
'            "Attaquant : HDV"+str(ton_hdv)+"\\n"\n'
'            "1) Compo optimale avec vraies troupes CoC et quantites\\n"\n'
'            "2) Sorts\\n3) Point d entree\\n4) Ordre deploiement\\n"\n'
'            "5) Pieges a eviter\\n6) Probabilite 3 etoiles"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(\n'
'            title="Attaque HDV"+hdv_str+" - "+type_base,\n'
'            description=result[:4000], color=0xE74C3C\n'
'        )\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Replays YouTube / Twitch / CCN ⭐", value=links, inline=False)\n'
'        embed.set_thumbnail(url=screenshot.url)\n'
'        embed.set_footer(text="Vision : Gemini | Strategie : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "attack", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="copybase", description="Screenshot → trouve 5 bases similaires sur FTB + CCN + CocBases")\n'
'    @app_commands.describe(screenshot="Screenshot de ta base")\n'
'    async def copybase(self, interaction: discord.Interaction, screenshot: discord.Attachment):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        await interaction.followup.send("🔍 Analyse en cours...")\n'
'        vision = await analyze_base_image(screenshot.url)\n'
'        hdv = vision.get("hdv",0)\n'
'        type_base = vision.get("type_base","unknown")\n'
'        style = vision.get("style","unknown")\n'
'        hdv_str = str(hdv) if hdv else "?"\n'
'        # FTB + CocBases + CCN + YouTube\n'
'        sources = await get_all_sources(\n'
'            "meilleure base "+type_base+" anti 3 etoiles",\n'
'            hdv if hdv else None, include_bases=True, base_type=type_base\n'
'        )\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            ctx+"\\n\\n"\n'
'            "Trouve 5 bases Clash of Clans de type "+type_base+" style "+style+" pour HDV"+hdv_str+".\\n"\n'
'            "Pour chaque base : description, points forts, contre quelles attaques elle est efficace.\\n"\n'
'            "Priorise les bases anti-3 etoiles."\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(\n'
'            title="Bases similaires HDV"+hdv_str+" - "+type_base,\n'
'            description=result[:4000], color=0x27AE60\n'
'        )\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="🔍 FTB | 🏰 CocBases | ⭐ ClashChamps Pro", value=links, inline=False)\n'
'        embed.set_thumbnail(url=screenshot.url)\n'
'        embed.set_footer(text="Vision : Gemini | Sources : FTB + CocBases + CCN")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "copybase", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="coach", description="Screenshot replay → coaching + erreurs + plan 2 semaines")\n'
'    @app_commands.describe(screenshot="Screenshot de ton replay", hdv="Ton HDV")\n'
'    async def coach(self, interaction: discord.Interaction, screenshot: discord.Attachment, hdv: int):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        await interaction.followup.send("🔍 Analyse de ton replay...")\n'
'        vision = await analyze_attack_image(screenshot.url)\n'
'        compo = vision.get("compo","inconnue")\n'
'        etoiles = vision.get("etoiles",0)\n'
'        erreurs = vision.get("erreurs",[])\n'
'        points_pos = vision.get("points_positifs",[])\n'
'        note = vision.get("note",5)\n'
'        sources = await get_all_sources(compo+" HDV"+str(hdv)+" tutoriel guide erreurs", hdv)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            "Coaching CoC base sur ce replay :\\n"\n'
'            "Compo : "+compo+" | Etoiles : "+str(etoiles)+"/3\\n"\n'
'            "Erreurs detectees : "+str(erreurs)+"\\n"\n'
'            "Points positifs : "+str(points_pos)+"\\n\\n"\n'
'            +ctx+"\\n\\n"\n'
'            "HDV : "+str(hdv)+"\\n"\n'
'            "1) Analyse detaillee des erreurs avec corrections\\n"\n'
'            "2) Ce qui a bien marche\\n"\n'
'            "3) Plan entrainement 2 semaines\\n"\n'
'            "4) Exercices pratiques specifiques\\n"\n'
'            "5) Note : "+str(note)+"/10 et comment progresser"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        stars = "⭐"*etoiles+"☆"*(3-etoiles)\n'
'        embed = discord.Embed(\n'
'            title="Coaching "+compo+" "+stars,\n'
'            description=result[:4000], color=0x8E44AD\n'
'        )\n'
'        embed.add_field(name="Compo detectee", value=compo, inline=True)\n'
'        embed.add_field(name="Etoiles", value=stars, inline=True)\n'
'        embed.add_field(name="Note IA", value=str(note)+"/10", inline=True)\n'
'        if erreurs:\n'
'            embed.add_field(name="Erreurs detectees", value="\\n".join(["❌ "+e for e in erreurs[:3]]), inline=False)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Tutoriels YouTube / Twitch / CCN ⭐", value=links, inline=False)\n'
'        embed.set_thumbnail(url=screenshot.url)\n'
'        embed.set_footer(text="Vision : Gemini | Coach : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "coach", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="piege", description="Screenshot base → detecte pieges + score dangerosite /10")\n'
'    @app_commands.describe(screenshot="Screenshot de la base", ta_compo="Ta compo d attaque")\n'
'    async def piege(self, interaction: discord.Interaction, screenshot: discord.Attachment, ta_compo: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        await interaction.followup.send("🔍 Analyse des pieges en cours...")\n'
'        vision = await analyze_base_image(screenshot.url)\n'
'        hdv = vision.get("hdv",0)\n'
'        type_base = vision.get("type_base","unknown")\n'
'        desc = vision.get("description","")\n'
'        hdv_str = str(hdv) if hdv else "?"\n'
'        sources = await get_all_sources("trap base piege HDV"+hdv_str, hdv if hdv else None)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            "Analyse pieges Clash of Clans.\\n"\n'
'            "Base : HDV"+hdv_str+" type "+type_base+"\\n"\n'
'            "Description : "+desc+"\\n"\n'
'            "Compo attaquante : "+ta_compo+"\\n\\n"\n'
'            +ctx+"\\n\\n"\n'
'            "1) Emplacements suspects de pieges (Giant Bomb, Air Mine, Skeleton Trap, Spring Trap)\\n"\n'
'            "2) Pieges les plus dangereux pour "+ta_compo+"\\n"\n'
'            "3) Score dangerosite global : /10\\n"\n'
'            "4) Zones a eviter absolument\\n"\n'
'            "5) Comment contourner ces pieges"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(\n'
'            title="Detection Pieges HDV"+hdv_str+" - "+type_base,\n'
'            description=result[:4000], color=0xE67E22\n'
'        )\n'
'        embed.set_thumbnail(url=screenshot.url)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Videos trap bases YouTube", value=links, inline=False)\n'
'        embed.set_footer(text="Vision : Gemini | IA : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "piege", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="add3star", description="Ajoute un replay 3 etoiles a la bibliotheque du clan")\n'
'    @app_commands.describe(hdv="HDV de la base", type_base="Type (diamond/box/ring/anti3)", compo="Compo utilisee", lien="Lien replay")\n'
'    async def add3star(self, interaction: discord.Interaction, hdv: int, type_base: str, compo: str, lien: str):\n'
'        await interaction.response.defer()\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute(\n'
'                "INSERT INTO replays_3stars (player_tag,guild_id,hdv,base_type,compo,lien,note,created) VALUES (?,?,?,?,?,?,?,?)",\n'
'                (str(interaction.user.id),str(interaction.guild_id),hdv,type_base,compo,lien,"3 etoiles",int(time.time()))\n'
'            )\n'
'            await db.commit()\n'
'        embed = discord.Embed(title="Replay 3 etoiles ajoute ! ⭐⭐⭐", color=0xF1C40F)\n'
'        embed.add_field(name="HDV", value=str(hdv), inline=True)\n'
'        embed.add_field(name="Type", value=type_base, inline=True)\n'
'        embed.add_field(name="Compo", value=compo, inline=True)\n'
'        embed.add_field(name="Lien", value=lien[:100], inline=False)\n'
'        embed.set_footer(text="Ajoute par "+str(interaction.user.name))\n'
'        await interaction.followup.send(embed=embed)\n'
'\n'
'    @app_commands.command(name="3stars", description="Cherche replays 3 etoiles dans la bibliotheque")\n'
'    @app_commands.describe(hdv="HDV", type_base="Type optionnel", compo="Compo optionnelle")\n'
'    async def stars3(self, interaction: discord.Interaction, hdv: int, type_base: str="", compo: str=""):\n'
'        await interaction.response.defer()\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            q = "SELECT player_tag,hdv,base_type,compo,lien,created FROM replays_3stars WHERE guild_id=? AND hdv=?"\n'
'            p = [str(interaction.guild_id),hdv]\n'
'            if type_base:\n'
'                q += " AND base_type=?"\n'
'                p.append(type_base)\n'
'            if compo:\n'
'                q += " AND compo LIKE ?"\n'
'                p.append("%"+compo+"%")\n'
'            q += " ORDER BY created DESC LIMIT 10"\n'
'            async with db.execute(q,p) as c:\n'
'                rows = await c.fetchall()\n'
'        if not rows:\n'
'            await interaction.followup.send("Aucun replay pour ces criteres.", ephemeral=True)\n'
'            return\n'
'        embed = discord.Embed(title="Replays 3 etoiles HDV"+str(hdv), color=0xF1C40F)\n'
'        for r in rows:\n'
'            embed.add_field(name=r[2]+" | "+r[3], value=r[4][:100], inline=False)\n'
'        embed.set_footer(text=str(len(rows))+" replays trouves")\n'
'        await interaction.followup.send(embed=embed)\n'
'\n'
'    @app_commands.command(name="mes3stars", description="Tes replays 3 etoiles classes par HDV")\n'
'    async def mes3stars(self, interaction: discord.Interaction):\n'
'        await interaction.response.defer()\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute(\n'
'                "SELECT hdv,base_type,compo,lien FROM replays_3stars WHERE player_tag=? ORDER BY hdv DESC,created DESC LIMIT 20",\n'
'                (str(interaction.user.id),)\n'
'            ) as c:\n'
'                rows = await c.fetchall()\n'
'        if not rows:\n'
'            await interaction.followup.send("Aucun replay enregistre.", ephemeral=True)\n'
'            return\n'
'        embed = discord.Embed(title="Tes replays 3 etoiles", color=0xF1C40F)\n'
'        for r in rows:\n'
'            embed.add_field(name="HDV"+str(r[0])+" | "+r[1]+" | "+r[2], value=r[3][:80], inline=False)\n'
'        await interaction.followup.send(embed=embed)\n'
'\n'
'    @app_commands.command(name="stats3stars", description="Rapport progression + compos efficaces")\n'
'    async def stats3stars(self, interaction: discord.Interaction):\n'
'        await interaction.response.defer()\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute(\n'
'                "SELECT hdv,compo,COUNT(*) as nb FROM replays_3stars WHERE player_tag=? GROUP BY hdv,compo ORDER BY nb DESC",\n'
'                (str(interaction.user.id),)\n'
'            ) as c:\n'
'                rows = await c.fetchall()\n'
'        if not rows:\n'
'            await interaction.followup.send("Aucune stat disponible.", ephemeral=True)\n'
'            return\n'
'        total = sum(r[2] for r in rows)\n'
'        prompt = (\n'
'            "Rapport progression CoC :\\n"\n'
'            +"\\n".join(["HDV"+str(r[0])+" "+r[1]+" x"+str(r[2]) for r in rows[:10]])\n'
'            +"\\nTotal : "+str(total)+" replays 3 etoiles.\\n"\n'
'            "1) Compos les plus efficaces\\n"\n'
'            "2) Progression observee\\n"\n'
'            "3) Recommandations pour progresser"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Stats 3 etoiles", description=result[:4000], color=0xF1C40F)\n'
'        embed.set_footer(text="Total : "+str(total)+" replays | IA : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'\n'
'    @app_commands.command(name="library", description="Bibliotheque clan HDV + type de base + FTB + CCN")\n'
'    @app_commands.describe(hdv="HDV", type_base="Type de base")\n'
'    async def library(self, interaction: discord.Interaction, hdv: int, type_base: str):\n'
'        await interaction.response.defer()\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute(\n'
'                "SELECT compo,lien FROM replays_3stars WHERE guild_id=? AND hdv=? AND base_type=? ORDER BY created DESC LIMIT 15",\n'
'                (str(interaction.guild_id),hdv,type_base)\n'
'            ) as c:\n'
'                rows = await c.fetchall()\n'
'        embed = discord.Embed(title="Bibliotheque HDV"+str(hdv)+" - "+type_base, color=0x8E44AD)\n'
'        if rows:\n'
'            for r in rows:\n'
'                embed.add_field(name=r[0], value=r[1][:80], inline=False)\n'
'        else:\n'
'            embed.description = "Aucun replay interne. Voici des ressources externes :"\n'
'        # Ajouter FTB + CCN\n'
'        from sources import search_findthisbase, search_cocbases, search_clashchamps, format_links\n'
'        import asyncio\n'
'        ftb = await asyncio.to_thread(search_findthisbase, hdv, type_base)\n'
'        ccn = await asyncio.to_thread(search_clashchamps, "base HDV"+str(hdv)+" "+type_base)\n'
'        all_src = ftb + ccn\n'
'        links = format_links(all_src)\n'
'        if links:\n'
'            embed.add_field(name="🔍 FTB | ⭐ ClashChamps Pro", value=links, inline=False)\n'
'        embed.set_footer(text=str(len(rows))+" replays internes + sources externes")\n'
'        await interaction.followup.send(embed=embed)\n'
'\n'
'    @app_commands.command(name="feedback", description="Avis sur une base ou replay (1-5)")\n'
'    @app_commands.describe(lien="Lien", note="Note 1-5", commentaire="Commentaire optionnel")\n'
'    async def feedback(self, interaction: discord.Interaction, lien: str, note: int, commentaire: str=""):\n'
'        await interaction.response.defer()\n'
'        if note < 1 or note > 5:\n'
'            await interaction.followup.send("Note entre 1 et 5.", ephemeral=True)\n'
'            return\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute(\n'
'                "INSERT INTO feedback (user_id,guild_id,lien,note,commentaire,created) VALUES (?,?,?,?,?,?)",\n'
'                (str(interaction.user.id),str(interaction.guild_id),lien,note,commentaire,int(time.time()))\n'
'            )\n'
'            await db.commit()\n'
'        embed = discord.Embed(title="Feedback enregistre !", color=0x2ECC71)\n'
'        embed.add_field(name="Note", value="⭐"*note, inline=True)\n'
'        embed.add_field(name="Lien", value=lien[:80], inline=True)\n'
'        if commentaire:\n'
'            embed.add_field(name="Commentaire", value=commentaire[:200], inline=False)\n'
'        embed.set_footer(text="Merci "+str(interaction.user.name)+" !")\n'
'        await interaction.followup.send(embed=embed)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Bases(bot))\n'
)
print("OK: cogs/bases.py")

# ══════════════════════════════════════════
# cogs/meta.py
# ══════════════════════════════════════════
open(f"{BASE}/cogs/meta.py", "w").write(
'import discord\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from database import log_command, is_blacklisted, check_rate_limit, get_cache, set_cache\n'
'from ai_cascade import ask_ai\n'
'from sources import get_all_sources, format_sources, format_links\n'
'\n'
'META = {\n'
'    18:"HDV18(380t): Zap Lalo=Golem de lave x4+Ballon x28+Haste x4+Foudre x2 | Dragbat=Dragon x10+Bat Spell x4+Rage x2 | Root Rider=Cavalier Racine x12+Super Barbare x8+Rage x3",\n'
'    17:"HDV17(360t): Zap Lalo=Golem de lave x4+Ballon x26+Foudre x2+Haste x4 | Dragbat=Dragon x9+Bat Spell x4 | Super Witch=Super Sorciere x6+Golem x3+Bowler x8",\n'
'    16:"HDV16(340t): Lalo=Golem de lave x3+Ballon x22+Rage x2+Haste x3 | Dragbat=Dragon x8+Bat Spell x3 | Hydra=Dragon x5+Electro Dragon x3+Rage x3",\n'
'    15:"HDV15(320t): Lalo=Golem de lave x3+Ballon x20+Rage x2+Haste x3 | Yeti Smash=Yeti x10+PEKKA x2+Bowler x8 | Dragbat=Dragon x8+Bat Spell x3",\n'
'    14:"HDV14(320t): Lalo=Golem de lave x3+Ballon x18+Haste x3 | Witch Slap=Witch x8+Golem x3+Bowler x6 | Yeti=Yeti x8+PEKKA x2+Bowler x6",\n'
'    13:"HDV13(300t): Lalo=Golem de lave x2+Ballon x18+Rage x2 | Queen Charge Lalo=Reine+Guerisseuse x4+Lalo | Yeti=Yeti x6+PEKKA x2+Bowler x5",\n'
'    12:"HDV12(280t): Lalo=Golem de lave x2+Ballon x16+Haste x2 | Queen Walk Dragon=Reine+Guerisseuse x4+Dragon x8 | Bowler Smash=Bowler x12+Golem x2+PEKKA x2",\n'
'    11:"HDV11(260t): Queen Walk Hog=Reine+Guerisseuse x4+Hog Rider x20 | Dragon=Dragon x10+Ballon x4+Rage x2 | GoWiPe=Golem x2+Sorcier x12+PEKKA x2",\n'
'    10:"HDV10(240t): GoHo=Golem x2+Hog Rider x18+Guerison x3 | Lavaloon=Golem de lave x2+Ballon x14+Haste x2 | Dragon=Dragon x8+Rage x2+Foudre x2",\n'
'    9:"HDV9(220t): GoWiPe=Golem x1+Sorcier x10+PEKKA x2+Rage x2 | Hog Rider=Hog Rider x20+Guerison x3 | Dragon=Dragon x7+Rage x2+Foudre x2",\n'
'}\n'
'\n'
'class Meta(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="meta", description="Meta CoC - YouTube + Twitch live + ClashChamps + tendances")\n'
'    @app_commands.describe(hdv="Ton HDV (1-18)")\n'
'    async def meta(self, interaction: discord.Interaction, hdv: int):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        if hdv < 1 or hdv > 18:\n'
'            await interaction.followup.send("HDV invalide (1-18).", ephemeral=True)\n'
'            return\n'
'        cache_key = "metav3_"+str(hdv)\n'
'        cached = await get_cache(cache_key)\n'
'        if cached:\n'
'            embed = discord.Embed(title="Meta HDV"+str(hdv)+" (cache 6h)", description=cached[:4000], color=0xE74C3C)\n'
'            await interaction.followup.send(embed=embed)\n'
'            return\n'
'        sources = await get_all_sources("meta meilleure armee attaque top 2025", hdv)\n'
'        ctx = format_sources(sources)\n'
'        meta_data = META.get(hdv,"HDV"+str(hdv))\n'
'        prompt = (\n'
'            "META REELLE CoC 2025 :\\n"+meta_data+"\\n\\n"\n'
'            "SOURCES YouTube/Twitch/ClashChamps :\\n"+ctx+"\\n\\n"\n'
'            "Meta complete HDV"+str(hdv)+" :\\n"\n'
'            "1) Top 5 compos avec troupes et quantites EXACTES\\n"\n'
'            "2) Tier list S/A/B/C avec win rate estime\\n"\n'
'            "3) Heros prioritaires et utilisation\\n"\n'
'            "4) Sorts recommandes\\n"\n'
'            "5) Compos a eviter\\n"\n'
'            "6) Tendances actuelles YouTube/Twitch"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        await set_cache(cache_key, result, source=ai_used, hours=6)\n'
'        embed = discord.Embed(title="Meta HDV"+str(hdv)+" CoC 2025", description=result[:4000], color=0xE74C3C)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="▶️ YouTube | 🟣 Twitch | ⭐ ClashChamps Pro", value=links, inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used+" | Sources : YouTube+Twitch+CCN | Cache 6h")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "meta", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="compo", description="Guide complet d une composition CoC + videos")\n'
'    @app_commands.describe(compo="Nom (Lalo, Dragbat, Zap Drag...)", hdv="Ton HDV")\n'
'    async def compo(self, interaction: discord.Interaction, compo: str, hdv: int):\n'
'        await interaction.response.defer()\n'
'        sources = await get_all_sources(compo+" guide attaque tutoriel", hdv)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            ctx+"\\n\\nGuide "+compo+" HDV"+str(hdv)+" :\\n"\n'
'            "1) Troupes exactes et quantites\\n"\n'
'            "2) Sorts\\n3) Ordre deploiement\\n"\n'
'            "4) Bases ideales\\n5) Erreurs a eviter\\n6) Difficulte /5"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title=compo+" HDV"+str(hdv), description=result[:4000], color=0x9B59B6)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Tutoriels YouTube / Twitch / CCN ⭐", value=links, inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "compo", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="tierlist", description="Tier list compos par HDV")\n'
'    @app_commands.describe(hdv="Ton HDV")\n'
'    async def tierlist(self, interaction: discord.Interaction, hdv: int):\n'
'        await interaction.response.defer()\n'
'        sources = await get_all_sources("tier list meilleures armees", hdv)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            "META REELLE : "+META.get(hdv,"HDV"+str(hdv))+"\\n\\n"\n'
'            +ctx+"\\n\\n"\n'
'            "Tier list HDV"+str(hdv)+" 2025 : S/A/B/C avec win rate et difficulte /5"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Tier List HDV"+str(hdv), description=result[:4000], color=0xF1C40F)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Sources", value=links, inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "tierlist", "ok", ai_used, cost)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Meta(bot))\n'
)
print("OK: cogs/meta.py")

# ══════════════════════════════════════════
# cogs/guerre.py
# ══════════════════════════════════════════
open(f"{BASE}/cogs/guerre.py", "w").write(
'import discord\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from database import log_command, is_blacklisted, check_rate_limit\n'
'from ai_cascade import ask_ai\n'
'from sources import get_all_sources, format_sources, format_links\n'
'\n'
'class Guerre(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="stratguerre", description="Strategie guerre de clan + YouTube + CCN")\n'
'    @app_commands.describe(taille="Taille (10v10...)", hdv_moyen="HDV moyen", style="agressif/defensif/equilibre")\n'
'    async def stratguerre(self, interaction: discord.Interaction, taille: str, hdv_moyen: int, style: str):\n'
'        await interaction.response.defer()\n'
'        sources = await get_all_sources("strategie guerre clan HDV"+str(hdv_moyen)+" "+style, hdv_moyen)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            ctx+"\\n\\nGuerre "+taille+" HDV moy "+str(hdv_moyen)+" style "+style+".\\n"\n'
'            "1) Plan general\\n2) Matchups recommandes\\n"\n'
'            "3) Compos avec vraies troupes CoC\\n"\n'
'            "4) Ordre attaques\\n5) Gestion etoiles\\n6) Plan B"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Strategie Guerre "+taille+" HDV"+str(hdv_moyen), description=result[:4000], color=0xE74C3C)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="YouTube / Twitch / CCN ⭐", value=links, inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "stratguerre", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="cwl", description="Guide CWL - Ligue de Guerre de Clans")\n'
'    @app_commands.describe(ligue="Ligue (Cristal/Maitre/Champion)", hdv="Ton HDV")\n'
'    async def cwl(self, interaction: discord.Interaction, ligue: str, hdv: int):\n'
'        await interaction.response.defer()\n'
'        sources = await get_all_sources("CWL "+ligue+" strategie", hdv)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            ctx+"\\n\\nGuide CWL "+ligue+" HDV"+str(hdv)+".\\n"\n'
'            "1) Meta CWL\\n2) Compos optimales avec vraies troupes\\n"\n'
'            "3) Strategie medailles\\n4) Erreurs a eviter"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Guide CWL "+ligue+" HDV"+str(hdv), description=result[:4000], color=0xF39C12)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Sources", value=links, inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "cwl", "ok", ai_used, cost)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Guerre(bot))\n'
)
print("OK: cogs/guerre.py")

# ══════════════════════════════════════════
# cogs/clan.py — API CoC
# ══════════════════════════════════════════
open(f"{BASE}/cogs/clan.py", "w").write(
'import discord, os, requests\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from database import log_command, is_blacklisted, check_rate_limit\n'
'from ai_cascade import ask_ai\n'
'from sources import get_all_sources, format_sources, format_links\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'COC_KEY = os.getenv("COC_API_KEY","")\n'
'\n'
'def coc_get(endpoint):\n'
'    try:\n'
'        r = requests.get("https://api.clashofclans.com/v1"+endpoint,\n'
'            headers={"Authorization":"Bearer "+COC_KEY}, timeout=5)\n'
'        if r.status_code == 200:\n'
'            return r.json()\n'
'    except Exception as e:\n'
'        print("[CoC]",e)\n'
'    return None\n'
'\n'
'class Clan(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="war", description="Analyse guerre en cours - fiche de chaque adversaire")\n'
'    @app_commands.describe(tag_clan="Tag clan (ex: #ABC123)")\n'
'    async def war(self, interaction: discord.Interaction, tag_clan: str):\n'
'        await interaction.response.defer()\n'
'        tag = tag_clan.replace("#","%23")\n'
'        data = coc_get("/clans/"+tag+"/currentwar")\n'
'        if not data or data.get("state")=="notInWar":\n'
'            await interaction.followup.send("Aucune guerre en cours.", ephemeral=True)\n'
'            return\n'
'        opp = data.get("opponent",{})\n'
'        members = opp.get("members",[])[:10]\n'
'        name = opp.get("name","Adversaire")\n'
'        size = data.get("teamSize",0)\n'
'        hdv_avg = sum(m.get("townhallLevel",0) for m in members)//max(len(members),1)\n'
'        sources = await get_all_sources("strategie guerre clan HDV"+str(hdv_avg), hdv_avg)\n'
'        ctx = format_sources(sources)\n'
'        membres_str = " | ".join([m.get("name","?")+"-HDV"+str(m.get("townhallLevel","?")) for m in members])\n'
'        prompt = (\n'
'            ctx+"\\n\\nGuerre "+str(size)+"v"+str(size)+" vs "+name+".\\n"\n'
'            "Adversaires : "+membres_str+"\\n"\n'
'            "1) Analyse composition adverse\\n2) Cibles prioritaires\\n"\n'
'            "3) Compos recommandees avec vraies troupes CoC\\n"\n'
'            "4) Strategie maximiser etoiles\\n5) Niveau menace /5"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Guerre vs "+name, description=result[:4000], color=0xE74C3C)\n'
'        embed.add_field(name="Taille", value=str(size)+"v"+str(size), inline=True)\n'
'        embed.add_field(name="HDV moy adverse", value=str(hdv_avg), inline=True)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Guides YouTube / CCN ⭐", value=links, inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used+" | API CoC")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "war", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="scout", description="Fiche complete clan ennemi - API CoC + CCN")\n'
'    @app_commands.describe(tag_clan="Tag clan ennemi")\n'
'    async def scout(self, interaction: discord.Interaction, tag_clan: str):\n'
'        await interaction.response.defer()\n'
'        data = coc_get("/clans/"+tag_clan.replace("#","%23"))\n'
'        if not data:\n'
'            await interaction.followup.send("Clan introuvable.", ephemeral=True)\n'
'            return\n'
'        name = data.get("name","?")\n'
'        members = data.get("memberList",[])[:15]\n'
'        th_counts = {}\n'
'        for m in members:\n'
'            th = m.get("townHallLevel",0)\n'
'            th_counts[th] = th_counts.get(th,0)+1\n'
'        th_str = " | ".join(["HDV"+str(k)+":"+str(v) for k,v in sorted(th_counts.items(),reverse=True)])\n'
'        hdv_avg = sum(th_counts.keys())//max(len(th_counts),1)\n'
'        sources = await get_all_sources("scout clan strategie", hdv_avg)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            ctx+"\\n\\nScouting : "+name+"\\n"\n'
'            "Composition : "+th_str+"\\n"\n'
'            "Niveau : "+str(data.get("clanLevel",0))+" | Wins : "+str(data.get("warWins",0))+"\\n"\n'
'            "1) Analyse composition\\n2) Points forts/faibles\\n"\n'
'            "3) Strategie pour les affronter\\n4) Menace /5"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Scout : "+name, description=result[:4000], color=0x8E44AD)\n'
'        embed.add_field(name="Niveau", value=str(data.get("clanLevel",0)), inline=True)\n'
'        embed.add_field(name="Membres", value=str(data.get("members",0)), inline=True)\n'
'        embed.add_field(name="Wins", value=str(data.get("warWins",0)), inline=True)\n'
'        embed.add_field(name="Composition", value=th_str[:200] if th_str else "N/A", inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used+" | API CoC")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "scout", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="predict", description="Probabilite victoire entre deux clans")\n'
'    @app_commands.describe(tag1="Ton clan", tag2="Clan adverse")\n'
'    async def predict(self, interaction: discord.Interaction, tag1: str, tag2: str):\n'
'        await interaction.response.defer()\n'
'        c1 = coc_get("/clans/"+tag1.replace("#","%23"))\n'
'        c2 = coc_get("/clans/"+tag2.replace("#","%23"))\n'
'        if not c1 or not c2:\n'
'            await interaction.followup.send("Clan(s) introuvable(s).", ephemeral=True)\n'
'            return\n'
'        def summ(c):\n'
'            m = c.get("memberList",[])[:15]\n'
'            avg = sum(x.get("townHallLevel",0) for x in m)//max(len(m),1)\n'
'            return c.get("name","?")+" HDVmoy:"+str(avg)+" Wins:"+str(c.get("warWins",0))+" NivClan:"+str(c.get("clanLevel",0))\n'
'        prompt = (\n'
'            "Prediction victoire CoC :\\n"\n'
'            "Clan 1 : "+summ(c1)+"\\n"\n'
'            "Clan 2 : "+summ(c2)+"\\n"\n'
'            "1) Probabilite % chaque clan\\n2) 3 matchups cles\\n"\n'
'            "3) Avantages de chacun\\n4) Facteur decisif\\n5) Confiance /10"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(\n'
'            title="Predict: "+c1.get("name","?")+" vs "+c2.get("name","?"),\n'
'            description=result[:4000], color=0xF39C12\n'
'        )\n'
'        embed.set_footer(text="IA : "+ai_used+" | API CoC")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "predict", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="progression", description="Top 5 upgrades urgents via API CoC")\n'
'    @app_commands.describe(tag_joueur="Tag joueur (ex: #ABC123)")\n'
'    async def progression(self, interaction: discord.Interaction, tag_joueur: str):\n'
'        await interaction.response.defer()\n'
'        p = coc_get("/players/"+tag_joueur.replace("#","%23"))\n'
'        if not p:\n'
'            await interaction.followup.send("Joueur introuvable.", ephemeral=True)\n'
'            return\n'
'        th = p.get("townHallLevel",0)\n'
'        heroes = p.get("heroes",[])\n'
'        troops = [t for t in p.get("troops",[]) if t.get("level",0)<t.get("maxLevel",1)][:5]\n'
'        hero_str = " | ".join([h.get("name","?")+str(h.get("level","?"))+"/"+str(h.get("maxLevel","?")) for h in heroes])\n'
'        troops_str = " | ".join([t.get("name","?")+str(t.get("level","?"))+"/"+str(t.get("maxLevel","?")) for t in troops])\n'
'        sources = await get_all_sources("guide progression HDV"+str(th), th)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            ctx+"\\n\\nPlan progression "+p.get("name","?")+" HDV"+str(th)+".\\n"\n'
'            "Heros : "+(hero_str or "aucun")+"\\n"\n'
'            "Troupes pas max : "+(troops_str or "tout max")+"\\n"\n'
'            "1) Top 5 upgrades URGENTS\\n2) Ordre optimal\\n"\n'
'            "3) Temps estime par upgrade\\n4) Ressources prioritaires"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Progression "+p.get("name","?")+" HDV"+str(th), description=result[:4000], color=0x27AE60)\n'
'        embed.add_field(name="Trophees", value=str(p.get("trophies",0)), inline=True)\n'
'        embed.add_field(name="HDV", value=str(th), inline=True)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Guides YouTube / CCN ⭐", value=links, inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used+" | API CoC")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "progression", "ok", ai_used, cost)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Clan(bot))\n'
)
print("OK: cogs/clan.py")

# ══════════════════════════════════════════
# cogs/info.py
# ══════════════════════════════════════════
open(f"{BASE}/cogs/info.py", "w").write(
'import discord\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from database import log_command, is_blacklisted, get_cache, set_cache\n'
'from ai_cascade import ask_ai\n'
'from sources import get_all_sources, format_sources, format_links\n'
'\n'
'class Info(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="aide", description="Que faire maintenant dans CoC ?")\n'
'    @app_commands.describe(hdv="Ton HDV", situation="Ta situation actuelle")\n'
'    async def aide(self, interaction: discord.Interaction, hdv: int, situation: str):\n'
'        await interaction.response.defer()\n'
'        sources = await get_all_sources("conseils progression HDV"+str(hdv), hdv)\n'
'        ctx = format_sources(sources)\n'
'        result, ai_used, cost = await ask_ai(\n'
'            ctx+"\\n\\nCoC HDV"+str(hdv)+" : "+situation+"\\nQue faire MAINTENANT ? 5 points actionnables."\n'
'        )\n'
'        embed = discord.Embed(title="Que faire ? HDV"+str(hdv), description=result[:4000], color=0x3498DB)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Ressources", value=links, inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "aide", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="patch", description="Dernieres mises a jour CoC")\n'
'    async def patch(self, interaction: discord.Interaction):\n'
'        await interaction.response.defer()\n'
'        cached = await get_cache("patchv3")\n'
'        if cached:\n'
'            embed = discord.Embed(title="Patch Notes CoC", description=cached[:4000], color=0x1ABC9C)\n'
'            await interaction.followup.send(embed=embed)\n'
'            return\n'
'        sources = await get_all_sources("update patch notes nouveautes 2025", None)\n'
'        ctx = format_sources(sources)\n'
'        result, ai_used, cost = await ask_ai(ctx+"\\n\\nResume mises a jour CoC 2025 : nouveautes, balance changes, impact meta.")\n'
'        await set_cache("patchv3", result, hours=6)\n'
'        embed = discord.Embed(title="Patch Notes CoC 2025", description=result[:4000], color=0x1ABC9C)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Sources", value=links, inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "patch", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="quiz", description="Quiz Clash of Clans !")\n'
'    async def quiz(self, interaction: discord.Interaction):\n'
'        await interaction.response.defer()\n'
'        result, ai_used, cost = await ask_ai(\n'
'            "Genere 5 questions quiz CoC avec reponses. Vraies troupes/batiments. Format : Q: [question] R: [reponse]"\n'
'        )\n'
'        embed = discord.Embed(title="Quiz Clash of Clans !", description=result[:4000], color=0xE67E22)\n'
'        embed.set_footer(text="IA : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "quiz", "ok", ai_used, cost)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Info(bot))\n'
)
print("OK: cogs/info.py")

# ══════════════════════════════════════════
# cogs/admin.py
# ══════════════════════════════════════════
open(f"{BASE}/cogs/admin.py", "w").write(
'import discord, os, time, aiosqlite\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'OWNER_ID = int(os.getenv("OWNER_ID","0"))\n'
'DB_PATH = os.getenv("DB_PATH","data/bot.db")\n'
'\n'
'class Admin(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="logs", description="[ADMIN] Derniers logs")\n'
'    async def logs(self, interaction: discord.Interaction):\n'
'        if interaction.user.id != OWNER_ID:\n'
'            await interaction.response.send_message("Acces refuse.", ephemeral=True)\n'
'            return\n'
'        await interaction.response.defer(ephemeral=True)\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute("SELECT user_id,command,result,ai_used,created FROM logs ORDER BY created DESC LIMIT 20") as c:\n'
'                rows = await c.fetchall()\n'
'        lines = ["Derniers logs :"]\n'
'        for r in rows:\n'
'            t = time.strftime("%H:%M",time.localtime(r[4]))\n'
'            lines.append(t+"|"+str(r[0])[:8]+"|"+r[1]+"|"+r[2]+"|"+r[3])\n'
'        await interaction.followup.send("```\\n"+"\\n".join(lines)+"\\n```", ephemeral=True)\n'
'\n'
'    @app_commands.command(name="stats", description="[ADMIN] Stats du bot")\n'
'    async def stats(self, interaction: discord.Interaction):\n'
'        if interaction.user.id != OWNER_ID:\n'
'            await interaction.response.send_message("Acces refuse.", ephemeral=True)\n'
'            return\n'
'        await interaction.response.defer(ephemeral=True)\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute("SELECT COUNT(*) FROM logs") as c:\n'
'                total = (await c.fetchone())[0]\n'
'            async with db.execute("SELECT COUNT(*) FROM cache") as c:\n'
'                cached = (await c.fetchone())[0]\n'
'        embed = discord.Embed(title="Stats Bot CoC", color=0x2ECC71)\n'
'        embed.add_field(name="Serveurs", value=str(len(self.bot.guilds)), inline=True)\n'
'        embed.add_field(name="Commandes", value=str(total), inline=True)\n'
'        embed.add_field(name="Cache", value=str(cached), inline=True)\n'
'        await interaction.followup.send(embed=embed, ephemeral=True)\n'
'\n'
'    @app_commands.command(name="blacklist", description="[ADMIN] Blacklister un user")\n'
'    @app_commands.describe(user_id="ID Discord", raison="Raison")\n'
'    async def blacklist_user(self, interaction: discord.Interaction, user_id: str, raison: str):\n'
'        if interaction.user.id != OWNER_ID:\n'
'            await interaction.response.send_message("Acces refuse.", ephemeral=True)\n'
'            return\n'
'        await interaction.response.defer(ephemeral=True)\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute("INSERT OR REPLACE INTO blacklist (user_id,reason,created) VALUES (?,?,?)",(user_id,raison,int(time.time())))\n'
'            await db.commit()\n'
'        await interaction.followup.send("Blackliste : "+user_id, ephemeral=True)\n'
'\n'
'    @app_commands.command(name="clearcache", description="[ADMIN] Vider le cache")\n'
'    async def clearcache(self, interaction: discord.Interaction):\n'
'        if interaction.user.id != OWNER_ID:\n'
'            await interaction.response.send_message("Acces refuse.", ephemeral=True)\n'
'            return\n'
'        await interaction.response.defer(ephemeral=True)\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute("DELETE FROM cache")\n'
'            await db.commit()\n'
'        await interaction.followup.send("Cache vide !", ephemeral=True)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Admin(bot))\n'
)
print("OK: cogs/admin.py")

# ══════════════════════════════════════════
# database.py
# ══════════════════════════════════════════
open(f"{BASE}/database.py", "w").write(
'import aiosqlite, time, os\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'DB_PATH = os.getenv("DB_PATH","data/bot.db")\n'
'\n'
'async def init_db():\n'
'    async with aiosqlite.connect(DB_PATH) as db:\n'
'        await db.executescript("""\n'
'            CREATE TABLE IF NOT EXISTS cache(cache_key TEXT PRIMARY KEY,value TEXT,source TEXT,created INTEGER);\n'
'            CREATE TABLE IF NOT EXISTS logs(id INTEGER PRIMARY KEY AUTOINCREMENT,guild_id TEXT,user_id TEXT,command TEXT,result TEXT,ai_used TEXT,cost REAL,created INTEGER);\n'
'            CREATE TABLE IF NOT EXISTS blacklist(user_id TEXT PRIMARY KEY,reason TEXT,created INTEGER);\n'
'            CREATE TABLE IF NOT EXISTS rate_limit(user_id TEXT PRIMARY KEY,count INTEGER,window_start INTEGER);\n'
'            CREATE TABLE IF NOT EXISTS feedback(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT,guild_id TEXT,lien TEXT,note INTEGER,commentaire TEXT,created INTEGER);\n'
'            CREATE TABLE IF NOT EXISTS replays_3stars(id INTEGER PRIMARY KEY AUTOINCREMENT,player_tag TEXT,guild_id TEXT,hdv INTEGER,base_type TEXT,compo TEXT,lien TEXT,note TEXT,created INTEGER);\n'
'        """)\n'
'        await db.commit()\n'
'\n'
'async def get_cache(key):\n'
'    try:\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute("SELECT value,created FROM cache WHERE cache_key=?",(key,)) as c:\n'
'                row = await c.fetchone()\n'
'                if row and (time.time()-row[1])<86400:\n'
'                    return row[0]\n'
'    except Exception:\n'
'        pass\n'
'    return None\n'
'\n'
'async def set_cache(key,value,source="",hours=24):\n'
'    try:\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute("INSERT OR REPLACE INTO cache(cache_key,value,source,created) VALUES(?,?,?,?)",(key,value,source,int(time.time())))\n'
'            await db.commit()\n'
'    except Exception:\n'
'        pass\n'
'\n'
'async def is_blacklisted(user_id):\n'
'    try:\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute("SELECT 1 FROM blacklist WHERE user_id=?",(user_id,)) as c:\n'
'                return await c.fetchone() is not None\n'
'    except Exception:\n'
'        return False\n'
'\n'
'async def check_rate_limit(user_id,limit=10,window=3600):\n'
'    try:\n'
'        now = int(time.time())\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute("SELECT count,window_start FROM rate_limit WHERE user_id=?",(user_id,)) as c:\n'
'                row = await c.fetchone()\n'
'            if row:\n'
'                count,start = row\n'
'                if now-start>window:\n'
'                    await db.execute("UPDATE rate_limit SET count=1,window_start=? WHERE user_id=?",(now,user_id))\n'
'                elif count>=limit:\n'
'                    await db.commit()\n'
'                    return False\n'
'                else:\n'
'                    await db.execute("UPDATE rate_limit SET count=count+1 WHERE user_id=?",(user_id,))\n'
'            else:\n'
'                await db.execute("INSERT INTO rate_limit(user_id,count,window_start) VALUES(?,1,?)",(user_id,now))\n'
'            await db.commit()\n'
'        return True\n'
'    except Exception:\n'
'        return True\n'
'\n'
'async def log_command(guild_id,user_id,command,result,ai_used="",cost=0.0):\n'
'    try:\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute("INSERT INTO logs(guild_id,user_id,command,result,ai_used,cost,created) VALUES(?,?,?,?,?,?,?)",(str(guild_id),str(user_id),command,result,ai_used,cost,int(time.time())))\n'
'            await db.commit()\n'
'    except Exception:\n'
'        pass\n'
)
print("OK: database.py")

# ══════════════════════════════════════════
# bot.py
# ══════════════════════════════════════════
open(f"{BASE}/bot.py", "w").write(
'import discord, asyncio, os\n'
'from discord.ext import commands\n'
'from dotenv import load_dotenv\n'
'from database import init_db\n'
'load_dotenv()\n'
'TOKEN = os.getenv("DISCORD_TOKEN","")\n'
'COGS = ["cogs.meta","cogs.guerre","cogs.bases","cogs.clan","cogs.info","cogs.admin"]\n'
'intents = discord.Intents.default()\n'
'intents.message_content = True\n'
'bot = commands.Bot(command_prefix="!", intents=intents)\n'
'\n'
'@bot.event\n'
'async def on_ready():\n'
'    print("Connecte : "+str(bot.user))\n'
'    print("Serveurs : "+str(len(bot.guilds)))\n'
'    try:\n'
'        synced = await bot.tree.sync()\n'
'        print("Commandes : "+str(len(synced)))\n'
'    except Exception as e:\n'
'        print("Erreur sync : "+str(e))\n'
'\n'
'async def main():\n'
'    await init_db()\n'
'    for cog in COGS:\n'
'        try:\n'
'            await bot.load_extension(cog)\n'
'            print("OK : "+cog)\n'
'        except Exception as e:\n'
'            print("ERREUR "+cog+" : "+str(e))\n'
'    await bot.start(TOKEN)\n'
'\n'
'asyncio.run(main())\n'
)
print("OK: bot.py")

print("\n"+"="*60)
print("REBUILD v3 COMPLET !")
print("="*60)
print("Sources : YouTube + Twitch + ClashChamps ⭐ + FTB 🔍 + CocBases 🏰")
print("Vision : Roboflow → Gemini Vision (analyse screenshots)")
print("IA : Groq (gratuit) → Gemini (fallback)")
print("")
print("Commandes avec SCREENSHOT :")
print("  /analysebase [img] [ton_hdv]   → Vision + replays")
print("  /attack [img] [ton_hdv]        → Vision + strategie")
print("  /copybase [img]                → Vision + FTB + CCN")
print("  /coach [img] [hdv]             → Vision + coaching")
print("  /piege [img] [compo]           → Vision + score /10")
print("")
print("Meta & Strategie :")
print("  /meta [hdv]  /compo  /tierlist  /stratguerre  /cwl")
print("")
print("Clan API CoC :")
print("  /war  /scout  /predict  /progression")
print("")
print("Bibliotheque replays :")
print("  /add3star  /3stars  /mes3stars  /stats3stars  /library  /feedback")
print("")
print("Info : /aide  /patch  /quiz")
print("Admin : /logs  /stats  /blacklist  /clearcache")
print("")
print("Lance : pkill -f 'python3 bot.py' && python3 bot.py")
