"""
REBUILD COMPLET DU BOT COC
- Analyse d'image via Gemini Vision
- YouTube recherche de replays
- Twitch streams live
- ClashChamps guides pro
Lance : python3 rebuild_all.py
"""
import os
BASE = os.path.expanduser("~/coc-bot")
os.makedirs(f"{BASE}/cogs", exist_ok=True)
os.makedirs(f"{BASE}/data", exist_ok=True)

# ══════════════════════════════════════════
# vision.py — Analyse d'image Gemini Vision
# ══════════════════════════════════════════
open(f"{BASE}/vision.py", "w").write(
'import os, asyncio, base64, requests as req\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'GEMINI_KEY = os.getenv("GEMINI_API_KEY", "")\n'
'\n'
'async def analyze_base_image(image_url: str) -> dict:\n'
'    """\n'
'    Analyse un screenshot de base CoC via Gemini Vision.\n'
'    Retourne : {hdv, type_base, style, description, confidence}\n'
'    """\n'
'    if not GEMINI_KEY:\n'
'        return {"hdv": 0, "type_base": "unknown", "style": "unknown", "description": "", "confidence": 0}\n'
'    try:\n'
'        # Telecharge l image\n'
'        r = req.get(image_url, timeout=10)\n'
'        img_b64 = base64.b64encode(r.content).decode()\n'
'        # Determine le type MIME\n'
'        content_type = r.headers.get("content-type", "image/png").split(";")[0]\n'
'        # Appel Gemini Vision\n'
'        from google import genai\n'
'        from google.genai import types\n'
'        client = genai.Client(api_key=GEMINI_KEY)\n'
'        prompt = (\n'
'            "Tu es un expert Clash of Clans. Analyse ce screenshot de base CoC.\\n"\n'
'            "Reponds UNIQUEMENT en JSON avec ces champs :\\n"\n'
'            "{\\n"\n'
'            "  \\"hdv\\": <numero HDV 1-18>,\\n"\n'
'            "  \\"type_base\\": <diamond|box|ring|anti3|hybrid>,\\n"\n'
'            "  \\"style\\": <anti_air|anti_ground|anti_3stars|anti_2stars|farming>,\\n"\n'
'            "  \\"description\\": <description courte de la base en francais>,\\n"\n'
'            "  \\"points_forts\\": <points forts de cette base>,\\n"\n'
'            "  \\"points_faibles\\": <points faibles de cette base>,\\n"\n'
'            "  \\"confidence\\": <0-100>\\n"\n'
'            "}"\n'
'        )\n'
'        response = await asyncio.to_thread(lambda: client.models.generate_content(\n'
'            model="gemini-1.5-flash",\n'
'            contents=[\n'
'                types.Part.from_bytes(data=r.content, mime_type=content_type),\n'
'                types.Part.from_text(text=prompt)\n'
'            ]\n'
'        ))\n'
'        text = response.text.strip()\n'
'        # Parse JSON\n'
'        import json, re\n'
'        match = re.search(r"\\{.*\\}", text, re.DOTALL)\n'
'        if match:\n'
'            data = json.loads(match.group())\n'
'            return data\n'
'    except Exception as e:\n'
'        print("[Vision]", e)\n'
'    return {"hdv": 0, "type_base": "unknown", "style": "unknown", "description": "Analyse impossible", "confidence": 0}\n'
'\n'
'async def analyze_attack_image(image_url: str) -> dict:\n'
'    """\n'
'    Analyse un screenshot de replay d attaque CoC.\n'
'    Retourne : {hdv_attaquant, hdv_defenseur, compo, etoiles, resultat, erreurs}\n'
'    """\n'
'    if not GEMINI_KEY:\n'
'        return {"hdv_attaquant": 0, "compo": "unknown", "etoiles": 0, "erreurs": []}\n'
'    try:\n'
'        r = req.get(image_url, timeout=10)\n'
'        content_type = r.headers.get("content-type", "image/png").split(";")[0]\n'
'        from google import genai\n'
'        from google.genai import types\n'
'        client = genai.Client(api_key=GEMINI_KEY)\n'
'        prompt = (\n'
'            "Tu es un expert Clash of Clans. Analyse ce screenshot de replay d attaque.\\n"\n'
'            "Reponds UNIQUEMENT en JSON :\\n"\n'
'            "{\\n"\n'
'            "  \\"compo\\": <composition detectee>,\\n"\n'
'            "  \\"etoiles\\": <0-3>,\\n"\n'
'            "  \\"pourcentage\\": <0-100>,\\n"\n'
'            "  \\"erreurs\\": [<liste des erreurs observees>],\\n"\n'
'            "  \\"points_positifs\\": [<ce qui a bien marche>],\\n"\n'
'            "  \\"note\\": <note /10>,\\n"\n'
'            "  \\"description\\": <description de l attaque>\\n"\n'
'            "}"\n'
'        )\n'
'        response = await asyncio.to_thread(lambda: client.models.generate_content(\n'
'            model="gemini-1.5-flash",\n'
'            contents=[\n'
'                types.Part.from_bytes(data=r.content, mime_type=content_type),\n'
'                types.Part.from_text(text=prompt)\n'
'            ]\n'
'        ))\n'
'        text = response.text.strip()\n'
'        import json, re\n'
'        match = re.search(r"\\{.*\\}", text, re.DOTALL)\n'
'        if match:\n'
'            return json.loads(match.group())\n'
'    except Exception as e:\n'
'        print("[Vision Attack]", e)\n'
'    return {"compo": "unknown", "etoiles": 0, "erreurs": [], "note": 5, "description": "Analyse impossible"}\n'
)
print("OK: vision.py")

# ══════════════════════════════════════════
# sources.py — YouTube + Twitch + CCN
# ══════════════════════════════════════════
open(f"{BASE}/sources.py", "w").write(
'import os, requests, asyncio\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'YT_KEY = os.getenv("YOUTUBE_API_KEY", "")\n'
'\n'
'def search_youtube(query, max_results=3, order="date"):\n'
'    if not YT_KEY:\n'
'        return []\n'
'    try:\n'
'        r = requests.get(\n'
'            "https://www.googleapis.com/youtube/v3/search",\n'
'            params={"part": "snippet", "q": query + " Clash of Clans 2025",\n'
'                    "type": "video", "maxResults": max_results,\n'
'                    "order": order, "key": YT_KEY},\n'
'            timeout=5\n'
'        )\n'
'        results = []\n'
'        for item in r.json().get("items", []):\n'
'            results.append({\n'
'                "source": "YouTube",\n'
'                "title": item["snippet"]["title"],\n'
'                "url": "https://youtu.be/" + item["id"]["videoId"],\n'
'                "desc": item["snippet"]["description"][:300],\n'
'                "channel": item["snippet"]["channelTitle"]\n'
'            })\n'
'        return results\n'
'    except Exception as e:\n'
'        print("[YouTube]", e)\n'
'        return []\n'
'\n'
'def search_twitch(query):\n'
'    try:\n'
'        r = requests.get(\n'
'            "https://api.twitch.tv/helix/search/channels",\n'
'            params={"query": query + " clash of clans", "live_only": "true", "first": 3},\n'
'            headers={"Client-ID": "kimne78kx3ncx6brgo4mv6wki5h1ko",\n'
'                     "Authorization": "Bearer " + os.getenv("TWITCH_TOKEN", "")},\n'
'            timeout=5\n'
'        )\n'
'        results = []\n'
'        for ch in r.json().get("data", []):\n'
'            results.append({\n'
'                "source": "Twitch",\n'
'                "title": ch.get("title", ch.get("display_name", "")),\n'
'                "url": "https://twitch.tv/" + ch.get("broadcaster_login", ""),\n'
'                "desc": "Stream live CoC : " + ch.get("game_name", ""),\n'
'                "channel": ch.get("display_name", "")\n'
'            })\n'
'        return results\n'
'    except Exception as e:\n'
'        print("[Twitch]", e)\n'
'        return []\n'
'\n'
'def search_clashchamps(query):\n'
'    try:\n'
'        from bs4 import BeautifulSoup\n'
'        r = requests.get(\n'
'            "https://clashchamps.com/?s=" + query.replace(" ", "+"),\n'
'            headers={"User-Agent": "Mozilla/5.0"}, timeout=5\n'
'        )\n'
'        soup = BeautifulSoup(r.text, "html.parser")\n'
'        results = []\n'
'        for article in soup.select("article")[:3]:\n'
'            a = article.select_one("h2 a") or article.select_one("h3 a")\n'
'            desc_el = article.select_one("p")\n'
'            if a:\n'
'                results.append({\n'
'                    "source": "ClashChamps",\n'
'                    "title": a.text.strip(),\n'
'                    "url": a.get("href", ""),\n'
'                    "desc": desc_el.text.strip()[:200] if desc_el else "Guide pro CoC",\n'
'                    "channel": "ClashChamps"\n'
'                })\n'
'        return results\n'
'    except Exception as e:\n'
'        print("[CCN]", e)\n'
'        return []\n'
'\n'
'async def get_all_sources(query, hdv=None):\n'
'    q = ("HDV" + str(hdv) + " " if hdv else "") + query\n'
'    results = []\n'
'    # YouTube en priorite\n'
'    yt = await asyncio.to_thread(search_youtube, q, 3)\n'
'    results += yt\n'
'    # Twitch\n'
'    tw = await asyncio.to_thread(search_twitch, query)\n'
'    results += tw\n'
'    # ClashChamps\n'
'    ccn = await asyncio.to_thread(search_clashchamps, q)\n'
'    results += ccn\n'
'    return results\n'
'\n'
'def format_sources(results):\n'
'    if not results:\n'
'        return ""\n'
'    lines = ["Sources recentes Clash of Clans :"]\n'
'    for r in results:\n'
'        icon = {"YouTube": "▶️", "Twitch": "🟣", "ClashChamps": "⭐"}.get(r["source"], "🔗")\n'
'        lines.append(icon + " [" + r["source"] + "] " + r["title"] + " : " + r["desc"][:150])\n'
'    return "\\n".join(lines)\n'
'\n'
'def format_links(results):\n'
'    if not results:\n'
'        return ""\n'
'    lines = []\n'
'    for r in results[:4]:\n'
'        icon = {"YouTube": "▶️", "Twitch": "🟣", "ClashChamps": "⭐"}.get(r["source"], "🔗")\n'
'        if r.get("url"):\n'
'            lines.append(icon + " [" + r["title"][:50] + "](" + r["url"] + ")")\n'
'    return "\\n".join(lines)\n'
)
print("OK: sources.py")

# ══════════════════════════════════════════
# cogs/bases.py — avec vision IA
# ══════════════════════════════════════════
open(f"{BASE}/cogs/bases.py", "w").write(
'import discord, os, time, aiosqlite\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from database import log_command, is_blacklisted, check_rate_limit, get_cache, set_cache\n'
'from ai_cascade import ask_ai\n'
'from sources import get_all_sources, format_sources, format_links\n'
'from vision import analyze_base_image, analyze_attack_image\n'
'\n'
'DB_PATH = os.getenv("DB_PATH", "data/bot.db")\n'
'\n'
'class Bases(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="analysebase", description="Envoie un screenshot de base - l IA analyse et trouve des replays")\n'
'    @app_commands.describe(screenshot="Screenshot de la base a analyser", ton_hdv="Ton HDV pour attaquer")\n'
'    async def analysebase(self, interaction: discord.Interaction, screenshot: discord.Attachment, ton_hdv: int):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        # Etape 1 : Analyse vision\n'
'        await interaction.followup.send("Analyse du screenshot en cours... 🔍")\n'
'        vision = await analyze_base_image(screenshot.url)\n'
'        hdv = vision.get("hdv", 0)\n'
'        type_base = vision.get("type_base", "unknown")\n'
'        style = vision.get("style", "unknown")\n'
'        desc = vision.get("description", "")\n'
'        points_faibles = vision.get("points_faibles", "")\n'
'        confidence = vision.get("confidence", 0)\n'
'        if hdv == 0:\n'
'            hdv_str = "inconnu"\n'
'        else:\n'
'            hdv_str = str(hdv)\n'
'        # Etape 2 : YouTube - replays de cette base\n'
'        query = type_base + " base HDV" + hdv_str + " attaque 3 etoiles replay"\n'
'        sources = await get_all_sources(query, hdv if hdv else None)\n'
'        ctx = format_sources(sources)\n'
'        # Etape 3 : Strategie via IA\n'
'        prompt = (\n'
'            "Analyse de base Clash of Clans detectee par IA :\\n"\n'
'            + "HDV detecte : " + hdv_str + "\\n"\n'
'            + "Type de base : " + type_base + "\\n"\n'
'            + "Style defensif : " + style + "\\n"\n'
'            + "Description : " + desc + "\\n"\n'
'            + "Points faibles detectes : " + points_faibles + "\\n"\n'
'            + "\\n" + ctx + "\\n\\n"\n'
'            + "Mon HDV attaquant : " + str(ton_hdv) + "\\n"\n'
'            + "Donne :\\n"\n'
'            + "1) Meilleure composition pour attaquer (vraies troupes CoC avec quantites)\\n"\n'
'            + "2) Point d entree ideal base sur le type " + type_base + "\\n"\n'
'            + "3) Sorts recommandes\\n"\n'
'            + "4) Ordre de deploiement etape par etape\\n"\n'
'            + "5) Pieges probables sur ce type de base\\n"\n'
'            + "6) Probabilite 2 etoiles et 3 etoiles"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        # Embed principal\n'
'        color = 0x2ECC71 if confidence > 80 else 0xE67E22\n'
'        embed = discord.Embed(\n'
'            title="Analyse Base HDV" + hdv_str + " - " + type_base,\n'
'            description=result[:4000],\n'
'            color=color\n'
'        )\n'
'        embed.add_field(name="HDV detecte", value=hdv_str, inline=True)\n'
'        embed.add_field(name="Type", value=type_base, inline=True)\n'
'        embed.add_field(name="Confiance IA", value=str(confidence)+"%", inline=True)\n'
'        if desc:\n'
'            embed.add_field(name="Description", value=desc[:200], inline=False)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Replays similaires YouTube/Twitch/CCN", value=links, inline=False)\n'
'        embed.set_thumbnail(url=screenshot.url)\n'
'        embed.set_footer(text="Vision : Gemini | Strategie : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "analysebase", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="attack", description="Screenshot de base - strategie d attaque complete + replays")\n'
'    @app_commands.describe(screenshot="Screenshot de la base adverse", ton_hdv="Ton HDV")\n'
'    async def attack(self, interaction: discord.Interaction, screenshot: discord.Attachment, ton_hdv: int):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        await interaction.followup.send("Analyse de la base en cours... 🔍")\n'
'        vision = await analyze_base_image(screenshot.url)\n'
'        hdv = vision.get("hdv", 0)\n'
'        type_base = vision.get("type_base", "unknown")\n'
'        points_faibles = vision.get("points_faibles", "")\n'
'        hdv_str = str(hdv) if hdv else "?"\n'
'        # Recherche replays YouTube pour ce type de base\n'
'        query = "attaque 3 etoiles " + type_base + " HDV" + hdv_str + " replay"\n'
'        sources = await get_all_sources(query, hdv if hdv else None)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            "Strategie d attaque Clash of Clans.\\n"\n'
'            + "Base adverse : HDV" + hdv_str + " type " + type_base + "\\n"\n'
'            + "Points faibles detectes : " + points_faibles + "\\n"\n'
'            + "\\n" + ctx + "\\n\\n"\n'
'            + "Attaquant : HDV" + str(ton_hdv) + "\\n"\n'
'            + "1) Composition optimale avec vraies troupes CoC\\n"\n'
'            + "2) Sorts\\n"\n'
'            + "3) Point d entree ideal\\n"\n'
'            + "4) Ordre de deploiement\\n"\n'
'            + "5) Pieges a eviter\\n"\n'
'            + "6) Probabilite 3 etoiles"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(\n'
'            title="Strategie Attaque - HDV" + hdv_str + " " + type_base,\n'
'            description=result[:4000],\n'
'            color=0xE74C3C\n'
'        )\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Replays YouTube/Twitch/CCN", value=links, inline=False)\n'
'        embed.set_thumbnail(url=screenshot.url)\n'
'        embed.set_footer(text="Vision : Gemini | Strategie : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "attack", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="copybase", description="Screenshot de base - trouve des bases similaires a copier")\n'
'    @app_commands.describe(screenshot="Screenshot de ta base actuelle")\n'
'    async def copybase(self, interaction: discord.Interaction, screenshot: discord.Attachment):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        await interaction.followup.send("Analyse du screenshot en cours... 🔍")\n'
'        vision = await analyze_base_image(screenshot.url)\n'
'        hdv = vision.get("hdv", 0)\n'
'        type_base = vision.get("type_base", "unknown")\n'
'        style = vision.get("style", "unknown")\n'
'        hdv_str = str(hdv) if hdv else "?"\n'
'        query = "meilleure base " + type_base + " HDV" + hdv_str + " anti 3 etoiles"\n'
'        sources = await get_all_sources(query, hdv if hdv else None)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            "Recherche de bases similaires Clash of Clans.\\n"\n'
'            + "Base detectee : HDV" + hdv_str + " type " + type_base + " style " + style + "\\n"\n'
'            + "\\n" + ctx + "\\n\\n"\n'
'            + "Propose 5 bases du meme type avec :\\n"\n'
'            + "1) Description de chaque base\\n"\n'
'            + "2) Points forts\\n"\n'
'            + "3) Comment les ameliorer\\n"\n'
'            + "4) Contre quelles attaques elles sont efficaces"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(\n'
'            title="Bases similaires HDV" + hdv_str + " - " + type_base,\n'
'            description=result[:4000],\n'
'            color=0x27AE60\n'
'        )\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Sources YouTube/CCN", value=links, inline=False)\n'
'        embed.set_thumbnail(url=screenshot.url)\n'
'        embed.set_footer(text="Vision : Gemini | IA : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "copybase", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="coach", description="Envoie un screenshot de replay - coaching personnalise")\n'
'    @app_commands.describe(screenshot="Screenshot de ton replay d attaque", hdv="Ton HDV")\n'
'    async def coach(self, interaction: discord.Interaction, screenshot: discord.Attachment, hdv: int):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        await interaction.followup.send("Analyse de ton replay en cours... 🔍")\n'
'        vision = await analyze_attack_image(screenshot.url)\n'
'        compo = vision.get("compo", "inconnue")\n'
'        etoiles = vision.get("etoiles", 0)\n'
'        erreurs = vision.get("erreurs", [])\n'
'        points_pos = vision.get("points_positifs", [])\n'
'        note = vision.get("note", 5)\n'
'        # Cherche des tutos YouTube pour cette compo\n'
'        sources = await get_all_sources(compo + " HDV" + str(hdv) + " tutoriel guide", hdv)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            "Coaching Clash of Clans base sur ce replay analyse :\\n"\n'
'            + "Composition detectee : " + compo + "\\n"\n'
'            + "Etoiles obtenues : " + str(etoiles) + "/3\\n"\n'
'            + "Erreurs detectees : " + str(erreurs) + "\\n"\n'
'            + "Points positifs : " + str(points_pos) + "\\n"\n'
'            + "\\n" + ctx + "\\n\\n"\n'
'            + "HDV du joueur : " + str(hdv) + "\\n"\n'
'            + "Donne un coaching complet :\\n"\n'
'            + "1) Analyse des erreurs avec corrections\\n"\n'
'            + "2) Ce qui a bien marche\\n"\n'
'            + "3) Plan d entrainement 2 semaines\\n"\n'
'            + "4) Exercices pratiques specifiques\\n"\n'
'            + "5) Note finale : " + str(note) + "/10 - comment progresser"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        stars_display = "⭐" * etoiles + "☆" * (3 - etoiles)\n'
'        embed = discord.Embed(\n'
'            title="Coaching - " + compo + " " + stars_display,\n'
'            description=result[:4000],\n'
'            color=0x8E44AD\n'
'        )\n'
'        embed.add_field(name="Compo detectee", value=compo, inline=True)\n'
'        embed.add_field(name="Etoiles", value=stars_display, inline=True)\n'
'        embed.add_field(name="Note IA", value=str(note)+"/10", inline=True)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Tutoriels YouTube/Twitch", value=links, inline=False)\n'
'        embed.set_thumbnail(url=screenshot.url)\n'
'        embed.set_footer(text="Vision : Gemini | Coach : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "coach", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="piege", description="Detecte les pieges sur un screenshot de base")\n'
'    @app_commands.describe(screenshot="Screenshot de la base suspecte", ta_compo="Ta compo d attaque")\n'
'    async def piege(self, interaction: discord.Interaction, screenshot: discord.Attachment, ta_compo: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        await interaction.followup.send("Analyse des pieges en cours... 🔍")\n'
'        vision = await analyze_base_image(screenshot.url)\n'
'        hdv = vision.get("hdv", 0)\n'
'        type_base = vision.get("type_base", "unknown")\n'
'        desc = vision.get("description", "")\n'
'        hdv_str = str(hdv) if hdv else "?"\n'
'        prompt = (\n'
'            "Analyse des pieges sur cette base Clash of Clans.\\n"\n'
'            + "Base : HDV" + hdv_str + " type " + type_base + "\\n"\n'
'            + "Description : " + desc + "\\n"\n'
'            + "Compo attaquante : " + ta_compo + "\\n"\n'
'            + "\\nDonne :\\n"\n'
'            + "1) Emplacements suspects de pieges\\n"\n'
'            + "2) Pieges les plus dangereux pour " + ta_compo + "\\n"\n'
'            + "3) Score de dangerosite : /10\\n"\n'
'            + "4) Zones a eviter absolument\\n"\n'
'            + "5) Comment contourner ces pieges"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(\n'
'            title="Detection Pieges - HDV" + hdv_str,\n'
'            description=result[:4000],\n'
'            color=0xE67E22\n'
'        )\n'
'        embed.set_thumbnail(url=screenshot.url)\n'
'        embed.set_footer(text="Vision : Gemini | IA : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "piege", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="add3star", description="Ajoute un replay 3 etoiles a la bibliotheque")\n'
'    @app_commands.describe(hdv="HDV de la base attackee", type_base="Type de base", compo="Compo utilisee", lien="Lien replay ou video")\n'
'    async def add3star(self, interaction: discord.Interaction, hdv: int, type_base: str, compo: str, lien: str):\n'
'        await interaction.response.defer()\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute(\n'
'                "INSERT INTO replays_3stars (player_tag, guild_id, hdv, base_type, compo, lien, note, created) VALUES (?,?,?,?,?,?,?,?)",\n'
'                (str(interaction.user.id), str(interaction.guild_id), hdv, type_base, compo, lien, "3 etoiles", int(time.time()))\n'
'            )\n'
'            await db.commit()\n'
'        embed = discord.Embed(title="Replay 3 etoiles ajoute !", color=0xF1C40F)\n'
'        embed.add_field(name="HDV", value=str(hdv), inline=True)\n'
'        embed.add_field(name="Type", value=type_base, inline=True)\n'
'        embed.add_field(name="Compo", value=compo, inline=True)\n'
'        embed.add_field(name="Lien", value=lien[:100], inline=False)\n'
'        await interaction.followup.send(embed=embed)\n'
'\n'
'    @app_commands.command(name="3stars", description="Cherche des replays 3 etoiles dans la bibliotheque")\n'
'    @app_commands.describe(hdv="HDV de la base", type_base="Type optionnel", compo="Compo optionnelle")\n'
'    async def stars3(self, interaction: discord.Interaction, hdv: int, type_base: str = "", compo: str = ""):\n'
'        await interaction.response.defer()\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            q = "SELECT player_tag, hdv, base_type, compo, lien FROM replays_3stars WHERE guild_id=? AND hdv=?"\n'
'            p = [str(interaction.guild_id), hdv]\n'
'            if type_base:\n'
'                q += " AND base_type=?"\n'
'                p.append(type_base)\n'
'            if compo:\n'
'                q += " AND compo LIKE ?"\n'
'                p.append("%" + compo + "%")\n'
'            q += " ORDER BY created DESC LIMIT 10"\n'
'            async with db.execute(q, p) as c:\n'
'                rows = await c.fetchall()\n'
'        if not rows:\n'
'            await interaction.followup.send("Aucun replay trouve.", ephemeral=True)\n'
'            return\n'
'        embed = discord.Embed(title="Replays 3 etoiles HDV"+str(hdv), color=0xF1C40F)\n'
'        for r in rows:\n'
'            embed.add_field(name=r[2]+" | "+r[3], value=r[4][:100], inline=False)\n'
'        await interaction.followup.send(embed=embed)\n'
'\n'
'    @app_commands.command(name="library", description="Bibliotheque du clan par HDV et type de base")\n'
'    @app_commands.describe(hdv="HDV", type_base="Type de base")\n'
'    async def library(self, interaction: discord.Interaction, hdv: int, type_base: str):\n'
'        await interaction.response.defer()\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute(\n'
'                "SELECT compo, lien FROM replays_3stars WHERE guild_id=? AND hdv=? AND base_type=? ORDER BY created DESC LIMIT 20",\n'
'                (str(interaction.guild_id), hdv, type_base)\n'
'            ) as c:\n'
'                rows = await c.fetchall()\n'
'        if not rows:\n'
'            await interaction.followup.send("Aucun replay pour HDV"+str(hdv)+" "+type_base+".", ephemeral=True)\n'
'            return\n'
'        embed = discord.Embed(title="Bibliotheque HDV"+str(hdv)+" - "+type_base, color=0x8E44AD)\n'
'        for r in rows:\n'
'            embed.add_field(name=r[0], value=r[1][:100], inline=False)\n'
'        await interaction.followup.send(embed=embed)\n'
'\n'
'    @app_commands.command(name="feedback", description="Avis sur une base ou replay (1-5)")\n'
'    @app_commands.describe(lien="Lien", note="Note 1-5", commentaire="Commentaire")\n'
'    async def feedback(self, interaction: discord.Interaction, lien: str, note: int, commentaire: str = ""):\n'
'        await interaction.response.defer()\n'
'        if note < 1 or note > 5:\n'
'            await interaction.followup.send("Note entre 1 et 5.", ephemeral=True)\n'
'            return\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute(\n'
'                "INSERT INTO feedback (user_id, guild_id, lien, note, commentaire, created) VALUES (?,?,?,?,?,?)",\n'
'                (str(interaction.user.id), str(interaction.guild_id), lien, note, commentaire, int(time.time()))\n'
'            )\n'
'            await db.commit()\n'
'        embed = discord.Embed(title="Feedback enregistre !", color=0x2ECC71)\n'
'        embed.add_field(name="Note", value="⭐"*note, inline=True)\n'
'        embed.add_field(name="Lien", value=lien[:100], inline=True)\n'
'        if commentaire:\n'
'            embed.add_field(name="Commentaire", value=commentaire[:200], inline=False)\n'
'        await interaction.followup.send(embed=embed)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Bases(bot))\n'
)
print("OK: cogs/bases.py")

# ══════════════════════════════════════════
# cogs/meta.py — avec YouTube + Twitch + CCN
# ══════════════════════════════════════════
open(f"{BASE}/cogs/meta.py", "w").write(
'import discord\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from database import log_command, is_blacklisted, check_rate_limit, get_cache, set_cache\n'
'from ai_cascade import ask_ai\n'
'from sources import get_all_sources, format_sources, format_links\n'
'\n'
'META_REELLE = {\n'
'    18: "HDV18 (380 troupes): TOP META - Zap Lalo: Golem de lave x4 + Ballon x28 + Haste x4 + Foudre x2 | Dragbat: Dragon x10 + Bat Spell x4 + Rage x2 | Root Rider: Cavalier Racine x12 + Super Barbare x8 | Blizzard Lalo: Sort Blizzard + Golem de lave x4 + Ballon x24",\n'
'    17: "HDV17 (360 troupes): Zap Lalo: Golem de lave x4 + Ballon x26 + Foudre x2 + Haste x4 | Dragbat: Dragon x9 + Bat Spell x4 | Super Witch: Super Sorciere x6 + Golem x3 + Bowler x8",\n'
'    16: "HDV16 (340 troupes): Lalo: Golem de lave x3 + Ballon x22 + Rage x2 + Haste x3 | Dragbat: Dragon x8 + Bat Spell x3 | Hydra: Dragon x5 + Electro Dragon x3",\n'
'    15: "HDV15 (320 troupes): Lalo: Golem de lave x3 + Ballon x20 + Rage x2 + Haste x3 | Yeti Smash: Yeti x10 + PEKKA x2 + Bowler x8 | Dragbat: Dragon x8 + Bat Spell x3",\n'
'    14: "HDV14 (320 troupes): Lalo: Golem de lave x3 + Ballon x18 + Haste x3 | Witch Slap: Witch x8 + Golem x3 + Bowler x6 | Yeti: Yeti x8 + PEKKA x2",\n'
'    13: "HDV13 (300 troupes): Lalo: Golem de lave x2 + Ballon x18 | Queen Charge Lalo: Reine + Guerisseuse x4 + Lalo | Yeti: Yeti x6 + PEKKA x2",\n'
'    12: "HDV12 (280 troupes): Lalo: Golem de lave x2 + Ballon x16 | Queen Walk Dragon: Reine + Guerisseuse x4 + Dragon x8 | Bowler Smash: Bowler x12 + Golem x2",\n'
'    11: "HDV11 (260 troupes): Queen Walk Hog: Reine + Guerisseuse x4 + Hog Rider x20 | Dragon: Dragon x10 + Ballon x4 + Rage x2 | GoWiPe: Golem x2 + Sorcier x12 + PEKKA x2",\n'
'    10: "HDV10 (240 troupes): GoHo: Golem x2 + Hog Rider x18 + Guerison x3 | Lavaloon: Golem de lave x2 + Ballon x14 | Dragon: Dragon x8 + Rage x2",\n'
'    9: "HDV9 (220 troupes): GoWiPe: Golem x1 + Sorcier x10 + PEKKA x2 | Hog Rider: Hog Rider x20 + Guerison x3 | Dragon: Dragon x7 + Rage x2",\n'
'}\n'
'\n'
'class Meta(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="meta", description="Meta actuelle CoC - YouTube + Twitch + ClashChamps")\n'
'    @app_commands.describe(hdv="Ton niveau HDV (1-18)")\n'
'    async def meta(self, interaction: discord.Interaction, hdv: int):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        if hdv < 1 or hdv > 18:\n'
'            await interaction.followup.send("HDV invalide (1-18).", ephemeral=True)\n'
'            return\n'
'        # Cache\n'
'        cache_key = "meta_v2_" + str(hdv)\n'
'        cached = await get_cache(cache_key)\n'
'        if cached:\n'
'            embed = discord.Embed(title="Meta HDV" + str(hdv) + " (cache)", description=cached[:4000], color=0xE74C3C)\n'
'            await interaction.followup.send(embed=embed)\n'
'            return\n'
'        # Sources YouTube + Twitch + CCN\n'
'        sources = await get_all_sources("meta meilleure armee attaque top", hdv)\n'
'        ctx = format_sources(sources)\n'
'        meta_data = META_REELLE.get(hdv, "HDV" + str(hdv))\n'
'        prompt = (\n'
'            "DONNEES META REELLES CoC :\\n" + meta_data + "\\n\\n"\n'
'            + "SOURCES RECENTES YouTube/Twitch/ClashChamps :\\n" + ctx + "\\n\\n"\n'
'            + "Donne la meta 2025 COMPLETE pour HDV" + str(hdv) + " :\\n"\n'
'            + "1) Top 5 compositions avec troupes et quantites EXACTES\\n"\n'
'            + "2) Tier list S/A/B/C avec win rate estime\\n"\n'
'            + "3) Heros prioritaires et usage\\n"\n'
'            + "4) Sorts recommandes\\n"\n'
'            + "5) Compositions a eviter\\n"\n'
'            + "6) Tendances actuelles basees sur YouTube et Twitch"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        await set_cache(cache_key, result, source=ai_used, hours=6)\n'
'        embed = discord.Embed(title="Meta HDV" + str(hdv) + " - CoC 2025", description=result[:4000], color=0xE74C3C)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Sources YouTube / Twitch / ClashChamps", value=links, inline=False)\n'
'        embed.set_footer(text="IA : " + ai_used + " | Sources : YouTube + Twitch + CCN")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "meta", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="compo", description="Guide complet d une composition CoC")\n'
'    @app_commands.describe(compo="Nom (ex: Lalo, Dragbat, Zap Drag)", hdv="Ton HDV")\n'
'    async def compo(self, interaction: discord.Interaction, compo: str, hdv: int):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        sources = await get_all_sources(compo + " guide attaque tutoriel", hdv)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            ctx + "\\n\\n"\n'
'            + "Guide complet de " + compo + " pour HDV" + str(hdv) + " :\\n"\n'
'            + "1) Troupes exactes et quantites\\n"\n'
'            + "2) Sorts\\n"\n'
'            + "3) Ordre de deploiement\\n"\n'
'            + "4) Bases ideales pour cette compo\\n"\n'
'            + "5) Erreurs a eviter\\n"\n'
'            + "6) Difficulte /5"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title=compo + " - HDV" + str(hdv), description=result[:4000], color=0x9B59B6)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Tutoriels YouTube/Twitch/CCN", value=links, inline=False)\n'
'        embed.set_footer(text="IA : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "compo", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="tierlist", description="Tier list des compos par HDV")\n'
'    @app_commands.describe(hdv="Ton HDV")\n'
'    async def tierlist(self, interaction: discord.Interaction, hdv: int):\n'
'        await interaction.response.defer()\n'
'        sources = await get_all_sources("tier list meilleures armees", hdv)\n'
'        ctx = format_sources(sources)\n'
'        meta_data = META_REELLE.get(hdv, "")\n'
'        prompt = (\n'
'            "DONNEES REELLES : " + meta_data + "\\n\\n"\n'
'            + ctx + "\\n\\n"\n'
'            + "Tier list HDV" + str(hdv) + " 2025 : S/A/B/C avec win rate et difficulte /5."\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Tier List HDV" + str(hdv), description=result[:4000], color=0xF1C40F)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Sources", value=links, inline=False)\n'
'        embed.set_footer(text="IA : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "tierlist", "ok", ai_used, cost)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Meta(bot))\n'
)
print("OK: cogs/meta.py")

# ══════════════════════════════════════════
# cogs/guerre.py
# ══════════════════════════════════════════
open(f"{BASE}/cogs/guerre.py", "w").write(
'import discord\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from database import log_command, is_blacklisted, check_rate_limit\n'
'from ai_cascade import ask_ai\n'
'from sources import get_all_sources, format_sources, format_links\n'
'\n'
'class Guerre(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="stratguerre", description="Strategie de guerre de clan CoC")\n'
'    @app_commands.describe(taille="Taille (10v10...)", hdv_moyen="HDV moyen", style="agressif/defensif/equilibre")\n'
'    async def stratguerre(self, interaction: discord.Interaction, taille: str, hdv_moyen: int, style: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        sources = await get_all_sources("strategie guerre clan HDV" + str(hdv_moyen), hdv_moyen)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            ctx + "\\n\\n"\n'
'            + "Strategie guerre " + taille + " HDV moyen " + str(hdv_moyen) + " style " + style + ".\\n"\n'
'            + "1) Plan general\\n2) Matchups recommandes\\n3) Compositions avec vraies troupes CoC\\n"\n'
'            + "4) Ordre des attaques\\n5) Gestion etoiles\\n6) Plan B"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Strategie Guerre " + taille + " HDV" + str(hdv_moyen), description=result[:4000], color=0xE74C3C)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Sources YouTube/Twitch/CCN", value=links, inline=False)\n'
'        embed.set_footer(text="IA : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "stratguerre", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="cwl", description="Guide CWL - Ligue de Guerre de Clans")\n'
'    @app_commands.describe(ligue="Ta ligue (Cristal/Maitre/Champion)", hdv="Ton HDV")\n'
'    async def cwl(self, interaction: discord.Interaction, ligue: str, hdv: int):\n'
'        await interaction.response.defer()\n'
'        sources = await get_all_sources("CWL " + ligue + " strategie", hdv)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            ctx + "\\n\\nGuide CWL " + ligue + " HDV" + str(hdv) + ".\\n"\n'
'            + "1) Meta CWL\\n2) Compos optimales\\n3) Strategie medailles\\n4) Erreurs a eviter"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Guide CWL " + ligue + " HDV" + str(hdv), description=result[:4000], color=0xF39C12)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Sources", value=links, inline=False)\n'
'        embed.set_footer(text="IA : " + ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "cwl", "ok", ai_used, cost)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Guerre(bot))\n'
)
print("OK: cogs/guerre.py")

# ══════════════════════════════════════════
# cogs/clan.py — API CoC
# ══════════════════════════════════════════
open(f"{BASE}/cogs/clan.py", "w").write(
'import discord, os, requests\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from database import log_command, is_blacklisted, check_rate_limit\n'
'from ai_cascade import ask_ai\n'
'from sources import get_all_sources, format_sources, format_links\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'COC_KEY = os.getenv("COC_API_KEY", "")\n'
'\n'
'def coc_get(endpoint):\n'
'    try:\n'
'        r = requests.get("https://api.clashofclans.com/v1" + endpoint,\n'
'            headers={"Authorization": "Bearer " + COC_KEY}, timeout=5)\n'
'        if r.status_code == 200:\n'
'            return r.json()\n'
'    except Exception as e:\n'
'        print("[CoC]", e)\n'
'    return None\n'
'\n'
'class Clan(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="war", description="Analyse de la guerre en cours")\n'
'    @app_commands.describe(tag_clan="Tag de ton clan (ex: #ABC123)")\n'
'    async def war(self, interaction: discord.Interaction, tag_clan: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        tag = tag_clan.replace("#", "%23")\n'
'        data = coc_get("/clans/" + tag + "/currentwar")\n'
'        if not data or data.get("state") == "notInWar":\n'
'            await interaction.followup.send("Aucune guerre en cours.", ephemeral=True)\n'
'            return\n'
'        opp = data.get("opponent", {})\n'
'        members = opp.get("members", [])[:10]\n'
'        name = opp.get("name", "Adversaire")\n'
'        size = data.get("teamSize", 0)\n'
'        hdv_avg = sum(m.get("townhallLevel",0) for m in members) // max(len(members),1)\n'
'        sources = await get_all_sources("strategie guerre clan HDV"+str(hdv_avg), hdv_avg)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            ctx + "\\n\\nGuerre " + str(size) + "v" + str(size) + " vs " + name + ".\\n"\n'
'            + "Membres adverses : " + " | ".join([m.get("name","?")+"-HDV"+str(m.get("townhallLevel","?")) for m in members]) + "\\n"\n'
'            + "1) Analyse composition adverse\\n2) Cibles prioritaires\\n"\n'
'            + "3) Compositions recommandees avec vraies troupes CoC\\n4) Strategie maximiser etoiles"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Guerre vs " + name, description=result[:4000], color=0xE74C3C)\n'
'        embed.add_field(name="Taille", value=str(size)+"v"+str(size), inline=True)\n'
'        embed.add_field(name="HDV moyen adverse", value=str(hdv_avg), inline=True)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Guides YouTube/CCN", value=links, inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used+" | API CoC")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "war", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="scout", description="Fiche complete d un clan ennemi")\n'
'    @app_commands.describe(tag_clan="Tag du clan (ex: #ABC123)")\n'
'    async def scout(self, interaction: discord.Interaction, tag_clan: str):\n'
'        await interaction.response.defer()\n'
'        tag = tag_clan.replace("#", "%23")\n'
'        data = coc_get("/clans/" + tag)\n'
'        if not data:\n'
'            await interaction.followup.send("Clan introuvable.", ephemeral=True)\n'
'            return\n'
'        name = data.get("name", "?")\n'
'        members = data.get("memberList", [])[:15]\n'
'        th_counts = {}\n'
'        for m in members:\n'
'            th = m.get("townHallLevel", 0)\n'
'            th_counts[th] = th_counts.get(th, 0) + 1\n'
'        th_str = " | ".join(["HDV"+str(k)+":"+str(v) for k,v in sorted(th_counts.items(), reverse=True)])\n'
'        hdv_avg = sum(th_counts.keys()) // max(len(th_counts),1)\n'
'        sources = await get_all_sources("scout clan CoC strategie", hdv_avg)\n'
'        ctx = format_sources(sources)\n'
'        prompt = (\n'
'            ctx + "\\n\\nScouting : " + name + "\\n"\n'
'            + "Composition : " + th_str + "\\n"\n'
'            + "Guerres gagnees : " + str(data.get("warWins",0)) + "\\n"\n'
'            + "1) Analyse composition\\n2) Points forts/faibles\\n"\n'
'            + "3) Strategie pour les affronter\\n4) Niveau menace /5"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Scout : " + name, description=result[:4000], color=0x8E44AD)\n'
'        embed.add_field(name="Niveau clan", value=str(data.get("clanLevel",0)), inline=True)\n'
'        embed.add_field(name="Membres", value=str(data.get("members",0)), inline=True)\n'
'        embed.add_field(name="Guerres gagnees", value=str(data.get("warWins",0)), inline=True)\n'
'        embed.add_field(name="Composition HDV", value=th_str[:200] if th_str else "N/A", inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used+" | API CoC")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "scout", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="predict", description="Probabilite de victoire entre deux clans")\n'
'    @app_commands.describe(tag1="Tag de ton clan", tag2="Tag du clan adverse")\n'
'    async def predict(self, interaction: discord.Interaction, tag1: str, tag2: str):\n'
'        await interaction.response.defer()\n'
'        c1 = coc_get("/clans/" + tag1.replace("#","%23"))\n'
'        c2 = coc_get("/clans/" + tag2.replace("#","%23"))\n'
'        if not c1 or not c2:\n'
'            await interaction.followup.send("Clan(s) introuvable(s).", ephemeral=True)\n'
'            return\n'
'        def summary(c):\n'
'            m = c.get("memberList",[])[:15]\n'
'            avg = sum(x.get("townHallLevel",0) for x in m)//max(len(m),1)\n'
'            return c.get("name","?")+" | HDV moy:"+str(avg)+" | Wins:"+str(c.get("warWins",0))\n'
'        prompt = (\n'
'            "Prediction victoire CoC :\\n"\n'
'            + "Clan 1 : "+summary(c1)+"\\n"\n'
'            + "Clan 2 : "+summary(c2)+"\\n"\n'
'            + "1) Probabilite % pour chaque clan\\n2) 3 matchups cles\\n"\n'
'            + "3) Avantages de chaque clan\\n4) Facteur decisif\\n5) Confiance /10"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Predict: "+c1.get("name","?")+" vs "+c2.get("name","?"), description=result[:4000], color=0xF39C12)\n'
'        embed.set_footer(text="IA : "+ai_used+" | API CoC")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "predict", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="progression", description="Plan de progression via API CoC")\n'
'    @app_commands.describe(tag_joueur="Ton tag joueur (ex: #ABC123)")\n'
'    async def progression(self, interaction: discord.Interaction, tag_joueur: str):\n'
'        await interaction.response.defer()\n'
'        tag = tag_joueur.replace("#", "%23")\n'
'        p = coc_get("/players/" + tag)\n'
'        if not p:\n'
'            await interaction.followup.send("Joueur introuvable.", ephemeral=True)\n'
'            return\n'
'        th = p.get("townHallLevel", 0)\n'
'        heroes = p.get("heroes", [])\n'
'        troops = [t for t in p.get("troops",[]) if t.get("level",0) < t.get("maxLevel",1)][:5]\n'
'        hero_str = " | ".join([h.get("name","?")+" "+str(h.get("level","?"))+"/"+str(h.get("maxLevel","?")) for h in heroes])\n'
'        troops_str = " | ".join([t.get("name","?")+" "+str(t.get("level","?"))+"/"+str(t.get("maxLevel","?")) for t in troops])\n'
'        prompt = (\n'
'            "Plan progression CoC pour " + p.get("name","?") + " HDV" + str(th) + ".\\n"\n'
'            + "Heros : " + (hero_str or "aucun") + "\\n"\n'
'            + "Troupes pas max : " + (troops_str or "tout max") + "\\n"\n'
'            + "1) Top 5 upgrades URGENTS\\n2) Ordre optimal\\n3) Temps estime\\n4) Ressources prioritaires"\n'
'        )\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Progression "+p.get("name","?")+" HDV"+str(th), description=result[:4000], color=0x27AE60)\n'
'        embed.add_field(name="Trophees", value=str(p.get("trophies",0)), inline=True)\n'
'        embed.add_field(name="HDV", value=str(th), inline=True)\n'
'        embed.set_footer(text="IA : "+ai_used+" | API CoC")\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "progression", "ok", ai_used, cost)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Clan(bot))\n'
)
print("OK: cogs/clan.py")

# ══════════════════════════════════════════
# cogs/info.py
# ══════════════════════════════════════════
open(f"{BASE}/cogs/info.py", "w").write(
'import discord\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from database import log_command, is_blacklisted, get_cache, set_cache\n'
'from ai_cascade import ask_ai\n'
'from sources import get_all_sources, format_sources, format_links\n'
'\n'
'class Info(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="aide", description="Que faire maintenant dans CoC ?")\n'
'    @app_commands.describe(hdv="Ton HDV", situation="Ta situation actuelle")\n'
'    async def aide(self, interaction: discord.Interaction, hdv: int, situation: str):\n'
'        await interaction.response.defer()\n'
'        if await is_blacklisted(str(interaction.user.id)):\n'
'            await interaction.followup.send("Blackliste.", ephemeral=True)\n'
'            return\n'
'        sources = await get_all_sources("conseils progression HDV"+str(hdv), hdv)\n'
'        ctx = format_sources(sources)\n'
'        prompt = ctx+"\\n\\nConseils CoC HDV"+str(hdv)+" : "+situation+"\\nQue faire MAINTENANT ? 5 points actionnables."\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Que faire ? HDV"+str(hdv), description=result[:4000], color=0x3498DB)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Ressources", value=links, inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "aide", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="patch", description="Dernieres mises a jour CoC")\n'
'    async def patch(self, interaction: discord.Interaction):\n'
'        await interaction.response.defer()\n'
'        cached = await get_cache("patch_v2")\n'
'        if cached:\n'
'            embed = discord.Embed(title="Patch Notes CoC", description=cached[:4000], color=0x1ABC9C)\n'
'            await interaction.followup.send(embed=embed)\n'
'            return\n'
'        sources = await get_all_sources("update patch notes nouveautes CoC 2025", None)\n'
'        ctx = format_sources(sources)\n'
'        prompt = ctx+"\\n\\nResume les dernieres mises a jour CoC 2025 : nouveautes, balance changes, impact meta."\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        await set_cache("patch_v2", result, hours=6)\n'
'        embed = discord.Embed(title="Patch Notes CoC 2025", description=result[:4000], color=0x1ABC9C)\n'
'        links = format_links(sources)\n'
'        if links:\n'
'            embed.add_field(name="Sources", value=links, inline=False)\n'
'        embed.set_footer(text="IA : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "patch", "ok", ai_used, cost)\n'
'\n'
'    @app_commands.command(name="quiz", description="Quiz Clash of Clans !")\n'
'    async def quiz(self, interaction: discord.Interaction):\n'
'        await interaction.response.defer()\n'
'        prompt = "Genere 5 questions quiz CoC avec reponses. Vraies troupes/batiments CoC. Format : Q: [question] R: [reponse]"\n'
'        result, ai_used, cost = await ask_ai(prompt)\n'
'        embed = discord.Embed(title="Quiz Clash of Clans !", description=result[:4000], color=0xE67E22)\n'
'        embed.set_footer(text="IA : "+ai_used)\n'
'        await interaction.followup.send(embed=embed)\n'
'        await log_command(interaction.guild_id, interaction.user.id, "quiz", "ok", ai_used, cost)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Info(bot))\n'
)
print("OK: cogs/info.py")

# ══════════════════════════════════════════
# cogs/admin.py
# ══════════════════════════════════════════
open(f"{BASE}/cogs/admin.py", "w").write(
'import discord, os, time, aiosqlite\n'
'from discord.ext import commands\n'
'from discord import app_commands\n'
'from dotenv import load_dotenv\n'
'load_dotenv()\n'
'OWNER_ID = int(os.getenv("OWNER_ID","0"))\n'
'DB_PATH = os.getenv("DB_PATH","data/bot.db")\n'
'\n'
'class Admin(commands.Cog):\n'
'    def __init__(self, bot):\n'
'        self.bot = bot\n'
'\n'
'    @app_commands.command(name="logs", description="[ADMIN] Derniers logs")\n'
'    async def logs(self, interaction: discord.Interaction):\n'
'        if interaction.user.id != OWNER_ID:\n'
'            await interaction.response.send_message("Acces refuse.", ephemeral=True)\n'
'            return\n'
'        await interaction.response.defer(ephemeral=True)\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute("SELECT user_id, command, result, ai_used, created FROM logs ORDER BY created DESC LIMIT 20") as c:\n'
'                rows = await c.fetchall()\n'
'        lines = ["Derniers logs :"]\n'
'        for r in rows:\n'
'            t = time.strftime("%H:%M", time.localtime(r[4]))\n'
'            lines.append(t+"|"+str(r[0])[:8]+"|"+r[1]+"|"+r[2]+"|"+r[3])\n'
'        await interaction.followup.send("```\\n"+"\\n".join(lines)+"\\n```", ephemeral=True)\n'
'\n'
'    @app_commands.command(name="stats", description="[ADMIN] Stats du bot")\n'
'    async def stats(self, interaction: discord.Interaction):\n'
'        if interaction.user.id != OWNER_ID:\n'
'            await interaction.response.send_message("Acces refuse.", ephemeral=True)\n'
'            return\n'
'        await interaction.response.defer(ephemeral=True)\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            async with db.execute("SELECT COUNT(*) FROM logs") as c:\n'
'                total = (await c.fetchone())[0]\n'
'            async with db.execute("SELECT COUNT(*) FROM cache") as c:\n'
'                cached = (await c.fetchone())[0]\n'
'        embed = discord.Embed(title="Stats Bot CoC", color=0x2ECC71)\n'
'        embed.add_field(name="Serveurs", value=str(len(self.bot.guilds)), inline=True)\n'
'        embed.add_field(name="Commandes totales", value=str(total), inline=True)\n'
'        embed.add_field(name="Cache", value=str(cached), inline=True)\n'
'        await interaction.followup.send(embed=embed, ephemeral=True)\n'
'\n'
'    @app_commands.command(name="blacklist", description="[ADMIN] Blacklister un user")\n'
'    @app_commands.describe(user_id="ID Discord", raison="Raison")\n'
'    async def blacklist_user(self, interaction: discord.Interaction, user_id: str, raison: str):\n'
'        if interaction.user.id != OWNER_ID:\n'
'            await interaction.response.send_message("Acces refuse.", ephemeral=True)\n'
'            return\n'
'        await interaction.response.defer(ephemeral=True)\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute("INSERT OR REPLACE INTO blacklist (user_id, reason, created) VALUES (?,?,?)", (user_id, raison, int(time.time())))\n'
'            await db.commit()\n'
'        await interaction.followup.send("Utilisateur "+user_id+" blackliste.", ephemeral=True)\n'
'\n'
'    @app_commands.command(name="clearcache", description="[ADMIN] Vider le cache")\n'
'    async def clearcache(self, interaction: discord.Interaction):\n'
'        if interaction.user.id != OWNER_ID:\n'
'            await interaction.response.send_message("Acces refuse.", ephemeral=True)\n'
'            return\n'
'        await interaction.response.defer(ephemeral=True)\n'
'        async with aiosqlite.connect(DB_PATH) as db:\n'
'            await db.execute("DELETE FROM cache")\n'
'            await db.commit()\n'
'        await interaction.followup.send("Cache vide !", ephemeral=True)\n'
'\n'
'async def setup(bot):\n'
'    await bot.add_cog(Admin(bot))\n'
)
print("OK: cogs/admin.py")

# ══════════════════════════════════════════
# bot.py
# ══════════════════════════════════════════
open(f"{BASE}/bot.py", "w").write(
'import discord, asyncio, os\n'
'from discord.ext import commands\n'
'from dotenv import load_dotenv\n'
'from database import init_db\n'
'load_dotenv()\n'
'TOKEN = os.getenv("DISCORD_TOKEN","")\n'
'COGS = ["cogs.meta","cogs.guerre","cogs.bases","cogs.clan","cogs.info","cogs.admin"]\n'
'intents = discord.Intents.default()\n'
'intents.message_content = True\n'
'bot = commands.Bot(command_prefix="!", intents=intents)\n'
'\n'
'@bot.event\n'
'async def on_ready():\n'
'    print("Connecte : "+str(bot.user))\n'
'    print("Serveurs : "+str(len(bot.guilds)))\n'
'    try:\n'
'        synced = await bot.tree.sync()\n'
'        print("Commandes : "+str(len(synced)))\n'
'    except Exception as e:\n'
'        print("Erreur sync : "+str(e))\n'
'\n'
'async def main():\n'
'    await init_db()\n'
'    for cog in COGS:\n'
'        try:\n'
'            await bot.load_extension(cog)\n'
'            print("OK : "+cog)\n'
'        except Exception as e:\n'
'            print("ERREUR "+cog+" : "+str(e))\n'
'    await bot.start(TOKEN)\n'
'\n'
'asyncio.run(main())\n'
)
print("OK: bot.py")

print("\n"+"="*50)
print("RECONSTRUCTION COMPLETE !")
print("="*50)
print("Commandes avec VISION IA (screenshot) :")
print("  /analysebase [screenshot] [ton_hdv]")
print("  /attack [screenshot] [ton_hdv]")
print("  /copybase [screenshot]")
print("  /coach [screenshot] [hdv]")
print("  /piege [screenshot] [ta_compo]")
print("\nCommandes meta avec YouTube+Twitch+CCN :")
print("  /meta [hdv]")
print("  /compo [compo] [hdv]")
print("  /tierlist [hdv]")
print("  /stratguerre [taille] [hdv] [style]")
print("  /cwl [ligue] [hdv]")
print("\nCommandes clan via API CoC :")
print("  /war [tag_clan]")
print("  /scout [tag_clan]")
print("  /predict [tag1] [tag2]")
print("  /progression [tag_joueur]")
print("\nBibliotheque replays :")
print("  /add3star /3stars /library /feedback")
print("\nInfos :")
print("  /aide /patch /quiz")
print("\nAdmin :")
print("  /logs /stats /blacklist /clearcache")
